// Code generated by ent, DO NOT EDIT.

package screenrunitem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the screenrunitem type in the database.
	Label = "screen_run_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScreenRunID holds the string denoting the screen_run_id field in the database.
	FieldScreenRunID = "screen_run_id"
	// FieldOrdinal holds the string denoting the ordinal field in the database.
	FieldOrdinal = "ordinal"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldPayloadJSON holds the string denoting the payload_json field in the database.
	FieldPayloadJSON = "payload_json"
	// Table holds the table name of the screenrunitem in the database.
	Table = "screen_run_items"
)

// Columns holds all SQL columns for screenrunitem fields.
var Columns = []string{
	FieldID,
	FieldScreenRunID,
	FieldOrdinal,
	FieldSymbol,
	FieldPayloadJSON,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ScreenRunIDValidator is a validator for the "screen_run_id" field. It is called by the builders before save.
	ScreenRunIDValidator func(string) error
	// OrdinalValidator is a validator for the "ordinal" field. It is called by the builders before save.
	OrdinalValidator func(int) error
	// DefaultSymbol holds the default value on creation for the "symbol" field.
	DefaultSymbol string
	// PayloadJSONValidator is a validator for the "payload_json" field. It is called by the builders before save.
	PayloadJSONValidator func([]byte) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ScreenRunItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScreenRunID orders the results by the screen_run_id field.
func ByScreenRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScreenRunID, opts...).ToFunc()
}

// ByOrdinal orders the results by the ordinal field.
func ByOrdinal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrdinal, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}
