// Code generated by ent, DO NOT EDIT.

package screenrunitem

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldContainsFold(FieldID, id))
}

// ScreenRunID applies equality check predicate on the "screen_run_id" field. It's identical to ScreenRunIDEQ.
func ScreenRunID(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldScreenRunID, v))
}

// Ordinal applies equality check predicate on the "ordinal" field. It's identical to OrdinalEQ.
func Ordinal(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldOrdinal, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldSymbol, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldPayloadJSON, v))
}

// ScreenRunIDEQ applies the EQ predicate on the "screen_run_id" field.
func ScreenRunIDEQ(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldScreenRunID, v))
}

// ScreenRunIDNEQ applies the NEQ predicate on the "screen_run_id" field.
func ScreenRunIDNEQ(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNEQ(FieldScreenRunID, v))
}

// ScreenRunIDIn applies the In predicate on the "screen_run_id" field.
func ScreenRunIDIn(vs ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldIn(FieldScreenRunID, vs...))
}

// ScreenRunIDNotIn applies the NotIn predicate on the "screen_run_id" field.
func ScreenRunIDNotIn(vs ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNotIn(FieldScreenRunID, vs...))
}

// ScreenRunIDGT applies the GT predicate on the "screen_run_id" field.
func ScreenRunIDGT(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGT(FieldScreenRunID, v))
}

// ScreenRunIDGTE applies the GTE predicate on the "screen_run_id" field.
func ScreenRunIDGTE(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGTE(FieldScreenRunID, v))
}

// ScreenRunIDLT applies the LT predicate on the "screen_run_id" field.
func ScreenRunIDLT(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLT(FieldScreenRunID, v))
}

// ScreenRunIDLTE applies the LTE predicate on the "screen_run_id" field.
func ScreenRunIDLTE(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLTE(FieldScreenRunID, v))
}

// ScreenRunIDContains applies the Contains predicate on the "screen_run_id" field.
func ScreenRunIDContains(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldContains(FieldScreenRunID, v))
}

// ScreenRunIDHasPrefix applies the HasPrefix predicate on the "screen_run_id" field.
func ScreenRunIDHasPrefix(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldHasPrefix(FieldScreenRunID, v))
}

// ScreenRunIDHasSuffix applies the HasSuffix predicate on the "screen_run_id" field.
func ScreenRunIDHasSuffix(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldHasSuffix(FieldScreenRunID, v))
}

// ScreenRunIDEqualFold applies the EqualFold predicate on the "screen_run_id" field.
func ScreenRunIDEqualFold(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEqualFold(FieldScreenRunID, v))
}

// ScreenRunIDContainsFold applies the ContainsFold predicate on the "screen_run_id" field.
func ScreenRunIDContainsFold(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldContainsFold(FieldScreenRunID, v))
}

// OrdinalEQ applies the EQ predicate on the "ordinal" field.
func OrdinalEQ(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldOrdinal, v))
}

// OrdinalNEQ applies the NEQ predicate on the "ordinal" field.
func OrdinalNEQ(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNEQ(FieldOrdinal, v))
}

// OrdinalIn applies the In predicate on the "ordinal" field.
func OrdinalIn(vs ...int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldIn(FieldOrdinal, vs...))
}

// OrdinalNotIn applies the NotIn predicate on the "ordinal" field.
func OrdinalNotIn(vs ...int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNotIn(FieldOrdinal, vs...))
}

// OrdinalGT applies the GT predicate on the "ordinal" field.
func OrdinalGT(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGT(FieldOrdinal, v))
}

// OrdinalGTE applies the GTE predicate on the "ordinal" field.
func OrdinalGTE(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGTE(FieldOrdinal, v))
}

// OrdinalLT applies the LT predicate on the "ordinal" field.
func OrdinalLT(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLT(FieldOrdinal, v))
}

// OrdinalLTE applies the LTE predicate on the "ordinal" field.
func OrdinalLTE(v int) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLTE(FieldOrdinal, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldContainsFold(FieldSymbol, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...[]byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...[]byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v []byte) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.FieldLTE(FieldPayloadJSON, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScreenRunItem) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScreenRunItem) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScreenRunItem) predicate.ScreenRunItem {
	return predicate.ScreenRunItem(sql.NotPredicates(p))
}
