// Code generated by ent, DO NOT EDIT.

package strategyversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldID, id))
}

// StrategyID applies equality check predicate on the "strategy_id" field. It's identical to StrategyIDEQ.
func StrategyID(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldStrategyID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldVersion, v))
}

// QueryText applies equality check predicate on the "query_text" field. It's identical to QueryTextEQ.
func QueryText(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldQueryText, v))
}

// QueryHash applies equality check predicate on the "query_hash" field. It's identical to QueryHashEQ.
func QueryHash(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldQueryHash, v))
}

// InputDataset applies equality check predicate on the "input_dataset" field. It's identical to InputDatasetEQ.
func InputDataset(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldInputDataset, v))
}

// InputSchemaVersion applies equality check predicate on the "input_schema_version" field. It's identical to InputSchemaVersionEQ.
func InputSchemaVersion(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldInputSchemaVersion, v))
}

// ParamsJSON applies equality check predicate on the "params_json" field. It's identical to ParamsJSONEQ.
func ParamsJSON(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldParamsJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldNote, v))
}

// StrategyIDEQ applies the EQ predicate on the "strategy_id" field.
func StrategyIDEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyIDNEQ applies the NEQ predicate on the "strategy_id" field.
func StrategyIDNEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldStrategyID, v))
}

// StrategyIDIn applies the In predicate on the "strategy_id" field.
func StrategyIDIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldStrategyID, vs...))
}

// StrategyIDNotIn applies the NotIn predicate on the "strategy_id" field.
func StrategyIDNotIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldStrategyID, vs...))
}

// StrategyIDGT applies the GT predicate on the "strategy_id" field.
func StrategyIDGT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldStrategyID, v))
}

// StrategyIDGTE applies the GTE predicate on the "strategy_id" field.
func StrategyIDGTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldStrategyID, v))
}

// StrategyIDLT applies the LT predicate on the "strategy_id" field.
func StrategyIDLT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldStrategyID, v))
}

// StrategyIDLTE applies the LTE predicate on the "strategy_id" field.
func StrategyIDLTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldStrategyID, v))
}

// StrategyIDContains applies the Contains predicate on the "strategy_id" field.
func StrategyIDContains(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContains(FieldStrategyID, v))
}

// StrategyIDHasPrefix applies the HasPrefix predicate on the "strategy_id" field.
func StrategyIDHasPrefix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasPrefix(FieldStrategyID, v))
}

// StrategyIDHasSuffix applies the HasSuffix predicate on the "strategy_id" field.
func StrategyIDHasSuffix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasSuffix(FieldStrategyID, v))
}

// StrategyIDEqualFold applies the EqualFold predicate on the "strategy_id" field.
func StrategyIDEqualFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldStrategyID, v))
}

// StrategyIDContainsFold applies the ContainsFold predicate on the "strategy_id" field.
func StrategyIDContainsFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldStrategyID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldVersion, v))
}

// QueryTextEQ applies the EQ predicate on the "query_text" field.
func QueryTextEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldQueryText, v))
}

// QueryTextNEQ applies the NEQ predicate on the "query_text" field.
func QueryTextNEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldQueryText, v))
}

// QueryTextIn applies the In predicate on the "query_text" field.
func QueryTextIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldQueryText, vs...))
}

// QueryTextNotIn applies the NotIn predicate on the "query_text" field.
func QueryTextNotIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldQueryText, vs...))
}

// QueryTextGT applies the GT predicate on the "query_text" field.
func QueryTextGT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldQueryText, v))
}

// QueryTextGTE applies the GTE predicate on the "query_text" field.
func QueryTextGTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldQueryText, v))
}

// QueryTextLT applies the LT predicate on the "query_text" field.
func QueryTextLT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldQueryText, v))
}

// QueryTextLTE applies the LTE predicate on the "query_text" field.
func QueryTextLTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldQueryText, v))
}

// QueryTextContains applies the Contains predicate on the "query_text" field.
func QueryTextContains(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContains(FieldQueryText, v))
}

// QueryTextHasPrefix applies the HasPrefix predicate on the "query_text" field.
func QueryTextHasPrefix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasPrefix(FieldQueryText, v))
}

// QueryTextHasSuffix applies the HasSuffix predicate on the "query_text" field.
func QueryTextHasSuffix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasSuffix(FieldQueryText, v))
}

// QueryTextEqualFold applies the EqualFold predicate on the "query_text" field.
func QueryTextEqualFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldQueryText, v))
}

// QueryTextContainsFold applies the ContainsFold predicate on the "query_text" field.
func QueryTextContainsFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldQueryText, v))
}

// QueryHashEQ applies the EQ predicate on the "query_hash" field.
func QueryHashEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldQueryHash, v))
}

// QueryHashNEQ applies the NEQ predicate on the "query_hash" field.
func QueryHashNEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldQueryHash, v))
}

// QueryHashIn applies the In predicate on the "query_hash" field.
func QueryHashIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldQueryHash, vs...))
}

// QueryHashNotIn applies the NotIn predicate on the "query_hash" field.
func QueryHashNotIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldQueryHash, vs...))
}

// QueryHashGT applies the GT predicate on the "query_hash" field.
func QueryHashGT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldQueryHash, v))
}

// QueryHashGTE applies the GTE predicate on the "query_hash" field.
func QueryHashGTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldQueryHash, v))
}

// QueryHashLT applies the LT predicate on the "query_hash" field.
func QueryHashLT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldQueryHash, v))
}

// QueryHashLTE applies the LTE predicate on the "query_hash" field.
func QueryHashLTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldQueryHash, v))
}

// QueryHashContains applies the Contains predicate on the "query_hash" field.
func QueryHashContains(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContains(FieldQueryHash, v))
}

// QueryHashHasPrefix applies the HasPrefix predicate on the "query_hash" field.
func QueryHashHasPrefix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasPrefix(FieldQueryHash, v))
}

// QueryHashHasSuffix applies the HasSuffix predicate on the "query_hash" field.
func QueryHashHasSuffix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasSuffix(FieldQueryHash, v))
}

// QueryHashEqualFold applies the EqualFold predicate on the "query_hash" field.
func QueryHashEqualFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldQueryHash, v))
}

// QueryHashContainsFold applies the ContainsFold predicate on the "query_hash" field.
func QueryHashContainsFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldQueryHash, v))
}

// InputDatasetEQ applies the EQ predicate on the "input_dataset" field.
func InputDatasetEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldInputDataset, v))
}

// InputDatasetNEQ applies the NEQ predicate on the "input_dataset" field.
func InputDatasetNEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldInputDataset, v))
}

// InputDatasetIn applies the In predicate on the "input_dataset" field.
func InputDatasetIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldInputDataset, vs...))
}

// InputDatasetNotIn applies the NotIn predicate on the "input_dataset" field.
func InputDatasetNotIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldInputDataset, vs...))
}

// InputDatasetGT applies the GT predicate on the "input_dataset" field.
func InputDatasetGT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldInputDataset, v))
}

// InputDatasetGTE applies the GTE predicate on the "input_dataset" field.
func InputDatasetGTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldInputDataset, v))
}

// InputDatasetLT applies the LT predicate on the "input_dataset" field.
func InputDatasetLT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldInputDataset, v))
}

// InputDatasetLTE applies the LTE predicate on the "input_dataset" field.
func InputDatasetLTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldInputDataset, v))
}

// InputDatasetContains applies the Contains predicate on the "input_dataset" field.
func InputDatasetContains(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContains(FieldInputDataset, v))
}

// InputDatasetHasPrefix applies the HasPrefix predicate on the "input_dataset" field.
func InputDatasetHasPrefix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasPrefix(FieldInputDataset, v))
}

// InputDatasetHasSuffix applies the HasSuffix predicate on the "input_dataset" field.
func InputDatasetHasSuffix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasSuffix(FieldInputDataset, v))
}

// InputDatasetEqualFold applies the EqualFold predicate on the "input_dataset" field.
func InputDatasetEqualFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldInputDataset, v))
}

// InputDatasetContainsFold applies the ContainsFold predicate on the "input_dataset" field.
func InputDatasetContainsFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldInputDataset, v))
}

// InputSchemaVersionEQ applies the EQ predicate on the "input_schema_version" field.
func InputSchemaVersionEQ(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldInputSchemaVersion, v))
}

// InputSchemaVersionNEQ applies the NEQ predicate on the "input_schema_version" field.
func InputSchemaVersionNEQ(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldInputSchemaVersion, v))
}

// InputSchemaVersionIn applies the In predicate on the "input_schema_version" field.
func InputSchemaVersionIn(vs ...int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldInputSchemaVersion, vs...))
}

// InputSchemaVersionNotIn applies the NotIn predicate on the "input_schema_version" field.
func InputSchemaVersionNotIn(vs ...int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldInputSchemaVersion, vs...))
}

// InputSchemaVersionGT applies the GT predicate on the "input_schema_version" field.
func InputSchemaVersionGT(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldInputSchemaVersion, v))
}

// InputSchemaVersionGTE applies the GTE predicate on the "input_schema_version" field.
func InputSchemaVersionGTE(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldInputSchemaVersion, v))
}

// InputSchemaVersionLT applies the LT predicate on the "input_schema_version" field.
func InputSchemaVersionLT(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldInputSchemaVersion, v))
}

// InputSchemaVersionLTE applies the LTE predicate on the "input_schema_version" field.
func InputSchemaVersionLTE(v int) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldInputSchemaVersion, v))
}

// ParamsJSONEQ applies the EQ predicate on the "params_json" field.
func ParamsJSONEQ(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldParamsJSON, v))
}

// ParamsJSONNEQ applies the NEQ predicate on the "params_json" field.
func ParamsJSONNEQ(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldParamsJSON, v))
}

// ParamsJSONIn applies the In predicate on the "params_json" field.
func ParamsJSONIn(vs ...[]byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldParamsJSON, vs...))
}

// ParamsJSONNotIn applies the NotIn predicate on the "params_json" field.
func ParamsJSONNotIn(vs ...[]byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldParamsJSON, vs...))
}

// ParamsJSONGT applies the GT predicate on the "params_json" field.
func ParamsJSONGT(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldParamsJSON, v))
}

// ParamsJSONGTE applies the GTE predicate on the "params_json" field.
func ParamsJSONGTE(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldParamsJSON, v))
}

// ParamsJSONLT applies the LT predicate on the "params_json" field.
func ParamsJSONLT(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldParamsJSON, v))
}

// ParamsJSONLTE applies the LTE predicate on the "params_json" field.
func ParamsJSONLTE(v []byte) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldParamsJSON, v))
}

// ParamsJSONIsNil applies the IsNil predicate on the "params_json" field.
func ParamsJSONIsNil() predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIsNull(FieldParamsJSON))
}

// ParamsJSONNotNil applies the NotNil predicate on the "params_json" field.
func ParamsJSONNotNil() predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotNull(FieldParamsJSON))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.FieldContainsFold(FieldNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StrategyVersion) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StrategyVersion) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StrategyVersion) predicate.StrategyVersion {
	return predicate.StrategyVersion(sql.NotPredicates(p))
}
