// Code generated by ent, DO NOT EDIT.

package dailybar

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dailybar type in the database.
	Label = "daily_bar"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderGroup holds the string denoting the provider_group field in the database.
	FieldProviderGroup = "provider_group"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldMarket holds the string denoting the market field in the database.
	FieldMarket = "market"
	// FieldSecurityType holds the string denoting the security_type field in the database.
	FieldSecurityType = "security_type"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldIsin holds the string denoting the isin field in the database.
	FieldIsin = "isin"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTradingDate holds the string denoting the trading_date field in the database.
	FieldTradingDate = "trading_date"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldOpeningPrice holds the string denoting the opening_price field in the database.
	FieldOpeningPrice = "opening_price"
	// FieldHighestPrice holds the string denoting the highest_price field in the database.
	FieldHighestPrice = "highest_price"
	// FieldLowestPrice holds the string denoting the lowest_price field in the database.
	FieldLowestPrice = "lowest_price"
	// FieldClosingPrice holds the string denoting the closing_price field in the database.
	FieldClosingPrice = "closing_price"
	// FieldPriceChangeFromPreviousClose holds the string denoting the price_change_from_previous_close field in the database.
	FieldPriceChangeFromPreviousClose = "price_change_from_previous_close"
	// FieldPriceChangeRateFromPreviousClose holds the string denoting the price_change_rate_from_previous_close field in the database.
	FieldPriceChangeRateFromPreviousClose = "price_change_rate_from_previous_close"
	// FieldTradedVolume holds the string denoting the traded_volume field in the database.
	FieldTradedVolume = "traded_volume"
	// FieldTradedAmount holds the string denoting the traded_amount field in the database.
	FieldTradedAmount = "traded_amount"
	// FieldMarketCapitalization holds the string denoting the market_capitalization field in the database.
	FieldMarketCapitalization = "market_capitalization"
	// FieldExtensionsJSON holds the string denoting the extensions_json field in the database.
	FieldExtensionsJSON = "extensions_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the dailybar in the database.
	Table = "daily_bar"
)

// Columns holds all SQL columns for dailybar fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldProviderGroup,
	FieldOperation,
	FieldMarket,
	FieldSecurityType,
	FieldSymbol,
	FieldIsin,
	FieldName,
	FieldTradingDate,
	FieldCurrency,
	FieldOpeningPrice,
	FieldHighestPrice,
	FieldLowestPrice,
	FieldClosingPrice,
	FieldPriceChangeFromPreviousClose,
	FieldPriceChangeRateFromPreviousClose,
	FieldTradedVolume,
	FieldTradedAmount,
	FieldMarketCapitalization,
	FieldExtensionsJSON,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderGroupValidator is a validator for the "provider_group" field. It is called by the builders before save.
	ProviderGroupValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// MarketValidator is a validator for the "market" field. It is called by the builders before save.
	MarketValidator func(string) error
	// SecurityTypeValidator is a validator for the "security_type" field. It is called by the builders before save.
	SecurityTypeValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// DefaultIsin holds the default value on creation for the "isin" field.
	DefaultIsin string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// TradingDateValidator is a validator for the "trading_date" field. It is called by the builders before save.
	TradingDateValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultOpeningPrice holds the default value on creation for the "opening_price" field.
	DefaultOpeningPrice string
	// DefaultHighestPrice holds the default value on creation for the "highest_price" field.
	DefaultHighestPrice string
	// DefaultLowestPrice holds the default value on creation for the "lowest_price" field.
	DefaultLowestPrice string
	// DefaultClosingPrice holds the default value on creation for the "closing_price" field.
	DefaultClosingPrice string
	// DefaultPriceChangeFromPreviousClose holds the default value on creation for the "price_change_from_previous_close" field.
	DefaultPriceChangeFromPreviousClose string
	// DefaultPriceChangeRateFromPreviousClose holds the default value on creation for the "price_change_rate_from_previous_close" field.
	DefaultPriceChangeRateFromPreviousClose string
	// DefaultTradedVolume holds the default value on creation for the "traded_volume" field.
	DefaultTradedVolume string
	// DefaultTradedAmount holds the default value on creation for the "traded_amount" field.
	DefaultTradedAmount string
	// DefaultMarketCapitalization holds the default value on creation for the "market_capitalization" field.
	DefaultMarketCapitalization string
	// DefaultExtensionsJSON holds the default value on creation for the "extensions_json" field.
	DefaultExtensionsJSON string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DailyBar queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderGroup orders the results by the provider_group field.
func ByProviderGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderGroup, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByMarket orders the results by the market field.
func ByMarket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarket, opts...).ToFunc()
}

// BySecurityType orders the results by the security_type field.
func BySecurityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecurityType, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByIsin orders the results by the isin field.
func ByIsin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsin, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTradingDate orders the results by the trading_date field.
func ByTradingDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradingDate, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByOpeningPrice orders the results by the opening_price field.
func ByOpeningPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningPrice, opts...).ToFunc()
}

// ByHighestPrice orders the results by the highest_price field.
func ByHighestPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighestPrice, opts...).ToFunc()
}

// ByLowestPrice orders the results by the lowest_price field.
func ByLowestPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLowestPrice, opts...).ToFunc()
}

// ByClosingPrice orders the results by the closing_price field.
func ByClosingPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosingPrice, opts...).ToFunc()
}

// ByPriceChangeFromPreviousClose orders the results by the price_change_from_previous_close field.
func ByPriceChangeFromPreviousClose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceChangeFromPreviousClose, opts...).ToFunc()
}

// ByPriceChangeRateFromPreviousClose orders the results by the price_change_rate_from_previous_close field.
func ByPriceChangeRateFromPreviousClose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceChangeRateFromPreviousClose, opts...).ToFunc()
}

// ByTradedVolume orders the results by the traded_volume field.
func ByTradedVolume(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradedVolume, opts...).ToFunc()
}

// ByTradedAmount orders the results by the traded_amount field.
func ByTradedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradedAmount, opts...).ToFunc()
}

// ByMarketCapitalization orders the results by the market_capitalization field.
func ByMarketCapitalization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketCapitalization, opts...).ToFunc()
}

// ByExtensionsJSON orders the results by the extensions_json field.
func ByExtensionsJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtensionsJSON, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
