// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/dailybar"
)

// DailyBarCreate is the builder for creating a DailyBar entity.
type DailyBarCreate struct {
	config
	mutation *DailyBarMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *DailyBarCreate) SetProvider(v string) *DailyBarCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderGroup sets the "provider_group" field.
func (_c *DailyBarCreate) SetProviderGroup(v string) *DailyBarCreate {
	_c.mutation.SetProviderGroup(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *DailyBarCreate) SetOperation(v string) *DailyBarCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetMarket sets the "market" field.
func (_c *DailyBarCreate) SetMarket(v string) *DailyBarCreate {
	_c.mutation.SetMarket(v)
	return _c
}

// SetSecurityType sets the "security_type" field.
func (_c *DailyBarCreate) SetSecurityType(v string) *DailyBarCreate {
	_c.mutation.SetSecurityType(v)
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *DailyBarCreate) SetSymbol(v string) *DailyBarCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetIsin sets the "isin" field.
func (_c *DailyBarCreate) SetIsin(v string) *DailyBarCreate {
	_c.mutation.SetIsin(v)
	return _c
}

// SetNillableIsin sets the "isin" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableIsin(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetIsin(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DailyBarCreate) SetName(v string) *DailyBarCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableName(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTradingDate sets the "trading_date" field.
func (_c *DailyBarCreate) SetTradingDate(v string) *DailyBarCreate {
	_c.mutation.SetTradingDate(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *DailyBarCreate) SetCurrency(v string) *DailyBarCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableCurrency(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetOpeningPrice sets the "opening_price" field.
func (_c *DailyBarCreate) SetOpeningPrice(v string) *DailyBarCreate {
	_c.mutation.SetOpeningPrice(v)
	return _c
}

// SetNillableOpeningPrice sets the "opening_price" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableOpeningPrice(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetOpeningPrice(*v)
	}
	return _c
}

// SetHighestPrice sets the "highest_price" field.
func (_c *DailyBarCreate) SetHighestPrice(v string) *DailyBarCreate {
	_c.mutation.SetHighestPrice(v)
	return _c
}

// SetNillableHighestPrice sets the "highest_price" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableHighestPrice(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetHighestPrice(*v)
	}
	return _c
}

// SetLowestPrice sets the "lowest_price" field.
func (_c *DailyBarCreate) SetLowestPrice(v string) *DailyBarCreate {
	_c.mutation.SetLowestPrice(v)
	return _c
}

// SetNillableLowestPrice sets the "lowest_price" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableLowestPrice(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetLowestPrice(*v)
	}
	return _c
}

// SetClosingPrice sets the "closing_price" field.
func (_c *DailyBarCreate) SetClosingPrice(v string) *DailyBarCreate {
	_c.mutation.SetClosingPrice(v)
	return _c
}

// SetNillableClosingPrice sets the "closing_price" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableClosingPrice(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetClosingPrice(*v)
	}
	return _c
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (_c *DailyBarCreate) SetPriceChangeFromPreviousClose(v string) *DailyBarCreate {
	_c.mutation.SetPriceChangeFromPreviousClose(v)
	return _c
}

// SetNillablePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillablePriceChangeFromPreviousClose(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetPriceChangeFromPreviousClose(*v)
	}
	return _c
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (_c *DailyBarCreate) SetPriceChangeRateFromPreviousClose(v string) *DailyBarCreate {
	_c.mutation.SetPriceChangeRateFromPreviousClose(v)
	return _c
}

// SetNillablePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillablePriceChangeRateFromPreviousClose(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetPriceChangeRateFromPreviousClose(*v)
	}
	return _c
}

// SetTradedVolume sets the "traded_volume" field.
func (_c *DailyBarCreate) SetTradedVolume(v string) *DailyBarCreate {
	_c.mutation.SetTradedVolume(v)
	return _c
}

// SetNillableTradedVolume sets the "traded_volume" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableTradedVolume(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetTradedVolume(*v)
	}
	return _c
}

// SetTradedAmount sets the "traded_amount" field.
func (_c *DailyBarCreate) SetTradedAmount(v string) *DailyBarCreate {
	_c.mutation.SetTradedAmount(v)
	return _c
}

// SetNillableTradedAmount sets the "traded_amount" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableTradedAmount(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetTradedAmount(*v)
	}
	return _c
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (_c *DailyBarCreate) SetMarketCapitalization(v string) *DailyBarCreate {
	_c.mutation.SetMarketCapitalization(v)
	return _c
}

// SetNillableMarketCapitalization sets the "market_capitalization" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableMarketCapitalization(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetMarketCapitalization(*v)
	}
	return _c
}

// SetExtensionsJSON sets the "extensions_json" field.
func (_c *DailyBarCreate) SetExtensionsJSON(v string) *DailyBarCreate {
	_c.mutation.SetExtensionsJSON(v)
	return _c
}

// SetNillableExtensionsJSON sets the "extensions_json" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableExtensionsJSON(v *string) *DailyBarCreate {
	if v != nil {
		_c.SetExtensionsJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DailyBarCreate) SetCreatedAt(v time.Time) *DailyBarCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableCreatedAt(v *time.Time) *DailyBarCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DailyBarCreate) SetUpdatedAt(v time.Time) *DailyBarCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DailyBarCreate) SetNillableUpdatedAt(v *time.Time) *DailyBarCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DailyBarMutation object of the builder.
func (_c *DailyBarCreate) Mutation() *DailyBarMutation {
	return _c.mutation
}

// Save creates the DailyBar in the database.
func (_c *DailyBarCreate) Save(ctx context.Context) (*DailyBar, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyBarCreate) SaveX(ctx context.Context) *DailyBar {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyBarCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyBarCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyBarCreate) defaults() {
	if _, ok := _c.mutation.Isin(); !ok {
		v := dailybar.DefaultIsin
		_c.mutation.SetIsin(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := dailybar.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := dailybar.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.OpeningPrice(); !ok {
		v := dailybar.DefaultOpeningPrice
		_c.mutation.SetOpeningPrice(v)
	}
	if _, ok := _c.mutation.HighestPrice(); !ok {
		v := dailybar.DefaultHighestPrice
		_c.mutation.SetHighestPrice(v)
	}
	if _, ok := _c.mutation.LowestPrice(); !ok {
		v := dailybar.DefaultLowestPrice
		_c.mutation.SetLowestPrice(v)
	}
	if _, ok := _c.mutation.ClosingPrice(); !ok {
		v := dailybar.DefaultClosingPrice
		_c.mutation.SetClosingPrice(v)
	}
	if _, ok := _c.mutation.PriceChangeFromPreviousClose(); !ok {
		v := dailybar.DefaultPriceChangeFromPreviousClose
		_c.mutation.SetPriceChangeFromPreviousClose(v)
	}
	if _, ok := _c.mutation.PriceChangeRateFromPreviousClose(); !ok {
		v := dailybar.DefaultPriceChangeRateFromPreviousClose
		_c.mutation.SetPriceChangeRateFromPreviousClose(v)
	}
	if _, ok := _c.mutation.TradedVolume(); !ok {
		v := dailybar.DefaultTradedVolume
		_c.mutation.SetTradedVolume(v)
	}
	if _, ok := _c.mutation.TradedAmount(); !ok {
		v := dailybar.DefaultTradedAmount
		_c.mutation.SetTradedAmount(v)
	}
	if _, ok := _c.mutation.MarketCapitalization(); !ok {
		v := dailybar.DefaultMarketCapitalization
		_c.mutation.SetMarketCapitalization(v)
	}
	if _, ok := _c.mutation.ExtensionsJSON(); !ok {
		v := dailybar.DefaultExtensionsJSON
		_c.mutation.SetExtensionsJSON(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dailybar.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dailybar.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyBarCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "DailyBar.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := dailybar.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderGroup(); !ok {
		return &ValidationError{Name: "provider_group", err: errors.New(`ent: missing required field "DailyBar.provider_group"`)}
	}
	if v, ok := _c.mutation.ProviderGroup(); ok {
		if err := dailybar.ProviderGroupValidator(v); err != nil {
			return &ValidationError{Name: "provider_group", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider_group": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "DailyBar.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := dailybar.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "DailyBar.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Market(); !ok {
		return &ValidationError{Name: "market", err: errors.New(`ent: missing required field "DailyBar.market"`)}
	}
	if v, ok := _c.mutation.Market(); ok {
		if err := dailybar.MarketValidator(v); err != nil {
			return &ValidationError{Name: "market", err: fmt.Errorf(`ent: validator failed for field "DailyBar.market": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecurityType(); !ok {
		return &ValidationError{Name: "security_type", err: errors.New(`ent: missing required field "DailyBar.security_type"`)}
	}
	if v, ok := _c.mutation.SecurityType(); ok {
		if err := dailybar.SecurityTypeValidator(v); err != nil {
			return &ValidationError{Name: "security_type", err: fmt.Errorf(`ent: validator failed for field "DailyBar.security_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "DailyBar.symbol"`)}
	}
	if v, ok := _c.mutation.Symbol(); ok {
		if err := dailybar.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "DailyBar.symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Isin(); !ok {
		return &ValidationError{Name: "isin", err: errors.New(`ent: missing required field "DailyBar.isin"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DailyBar.name"`)}
	}
	if _, ok := _c.mutation.TradingDate(); !ok {
		return &ValidationError{Name: "trading_date", err: errors.New(`ent: missing required field "DailyBar.trading_date"`)}
	}
	if v, ok := _c.mutation.TradingDate(); ok {
		if err := dailybar.TradingDateValidator(v); err != nil {
			return &ValidationError{Name: "trading_date", err: fmt.Errorf(`ent: validator failed for field "DailyBar.trading_date": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "DailyBar.currency"`)}
	}
	if _, ok := _c.mutation.OpeningPrice(); !ok {
		return &ValidationError{Name: "opening_price", err: errors.New(`ent: missing required field "DailyBar.opening_price"`)}
	}
	if _, ok := _c.mutation.HighestPrice(); !ok {
		return &ValidationError{Name: "highest_price", err: errors.New(`ent: missing required field "DailyBar.highest_price"`)}
	}
	if _, ok := _c.mutation.LowestPrice(); !ok {
		return &ValidationError{Name: "lowest_price", err: errors.New(`ent: missing required field "DailyBar.lowest_price"`)}
	}
	if _, ok := _c.mutation.ClosingPrice(); !ok {
		return &ValidationError{Name: "closing_price", err: errors.New(`ent: missing required field "DailyBar.closing_price"`)}
	}
	if _, ok := _c.mutation.PriceChangeFromPreviousClose(); !ok {
		return &ValidationError{Name: "price_change_from_previous_close", err: errors.New(`ent: missing required field "DailyBar.price_change_from_previous_close"`)}
	}
	if _, ok := _c.mutation.PriceChangeRateFromPreviousClose(); !ok {
		return &ValidationError{Name: "price_change_rate_from_previous_close", err: errors.New(`ent: missing required field "DailyBar.price_change_rate_from_previous_close"`)}
	}
	if _, ok := _c.mutation.TradedVolume(); !ok {
		return &ValidationError{Name: "traded_volume", err: errors.New(`ent: missing required field "DailyBar.traded_volume"`)}
	}
	if _, ok := _c.mutation.TradedAmount(); !ok {
		return &ValidationError{Name: "traded_amount", err: errors.New(`ent: missing required field "DailyBar.traded_amount"`)}
	}
	if _, ok := _c.mutation.MarketCapitalization(); !ok {
		return &ValidationError{Name: "market_capitalization", err: errors.New(`ent: missing required field "DailyBar.market_capitalization"`)}
	}
	if _, ok := _c.mutation.ExtensionsJSON(); !ok {
		return &ValidationError{Name: "extensions_json", err: errors.New(`ent: missing required field "DailyBar.extensions_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyBar.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DailyBar.updated_at"`)}
	}
	return nil
}

func (_c *DailyBarCreate) sqlSave(ctx context.Context) (*DailyBar, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyBarCreate) createSpec() (*DailyBar, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyBar{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailybar.Table, sqlgraph.NewFieldSpec(dailybar.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(dailybar.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderGroup(); ok {
		_spec.SetField(dailybar.FieldProviderGroup, field.TypeString, value)
		_node.ProviderGroup = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(dailybar.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Market(); ok {
		_spec.SetField(dailybar.FieldMarket, field.TypeString, value)
		_node.Market = value
	}
	if value, ok := _c.mutation.SecurityType(); ok {
		_spec.SetField(dailybar.FieldSecurityType, field.TypeString, value)
		_node.SecurityType = value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(dailybar.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := _c.mutation.Isin(); ok {
		_spec.SetField(dailybar.FieldIsin, field.TypeString, value)
		_node.Isin = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dailybar.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TradingDate(); ok {
		_spec.SetField(dailybar.FieldTradingDate, field.TypeString, value)
		_node.TradingDate = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(dailybar.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.OpeningPrice(); ok {
		_spec.SetField(dailybar.FieldOpeningPrice, field.TypeString, value)
		_node.OpeningPrice = value
	}
	if value, ok := _c.mutation.HighestPrice(); ok {
		_spec.SetField(dailybar.FieldHighestPrice, field.TypeString, value)
		_node.HighestPrice = value
	}
	if value, ok := _c.mutation.LowestPrice(); ok {
		_spec.SetField(dailybar.FieldLowestPrice, field.TypeString, value)
		_node.LowestPrice = value
	}
	if value, ok := _c.mutation.ClosingPrice(); ok {
		_spec.SetField(dailybar.FieldClosingPrice, field.TypeString, value)
		_node.ClosingPrice = value
	}
	if value, ok := _c.mutation.PriceChangeFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeFromPreviousClose, field.TypeString, value)
		_node.PriceChangeFromPreviousClose = value
	}
	if value, ok := _c.mutation.PriceChangeRateFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeRateFromPreviousClose, field.TypeString, value)
		_node.PriceChangeRateFromPreviousClose = value
	}
	if value, ok := _c.mutation.TradedVolume(); ok {
		_spec.SetField(dailybar.FieldTradedVolume, field.TypeString, value)
		_node.TradedVolume = value
	}
	if value, ok := _c.mutation.TradedAmount(); ok {
		_spec.SetField(dailybar.FieldTradedAmount, field.TypeString, value)
		_node.TradedAmount = value
	}
	if value, ok := _c.mutation.MarketCapitalization(); ok {
		_spec.SetField(dailybar.FieldMarketCapitalization, field.TypeString, value)
		_node.MarketCapitalization = value
	}
	if value, ok := _c.mutation.ExtensionsJSON(); ok {
		_spec.SetField(dailybar.FieldExtensionsJSON, field.TypeString, value)
		_node.ExtensionsJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dailybar.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dailybar.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyBar.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyBarUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyBarCreate) OnConflict(opts ...sql.ConflictOption) *DailyBarUpsertOne {
	_c.conflict = opts
	return &DailyBarUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyBarCreate) OnConflictColumns(columns ...string) *DailyBarUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyBarUpsertOne{
		create: _c,
	}
}

type (
	// DailyBarUpsertOne is the builder for "upsert"-ing
	//  one DailyBar node.
	DailyBarUpsertOne struct {
		create *DailyBarCreate
	}

	// DailyBarUpsert is the "OnConflict" setter.
	DailyBarUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *DailyBarUpsert) SetProvider(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateProvider() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldProvider)
	return u
}

// SetProviderGroup sets the "provider_group" field.
func (u *DailyBarUpsert) SetProviderGroup(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldProviderGroup, v)
	return u
}

// UpdateProviderGroup sets the "provider_group" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateProviderGroup() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldProviderGroup)
	return u
}

// SetOperation sets the "operation" field.
func (u *DailyBarUpsert) SetOperation(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateOperation() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldOperation)
	return u
}

// SetMarket sets the "market" field.
func (u *DailyBarUpsert) SetMarket(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldMarket, v)
	return u
}

// UpdateMarket sets the "market" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateMarket() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldMarket)
	return u
}

// SetSecurityType sets the "security_type" field.
func (u *DailyBarUpsert) SetSecurityType(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldSecurityType, v)
	return u
}

// UpdateSecurityType sets the "security_type" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateSecurityType() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldSecurityType)
	return u
}

// SetSymbol sets the "symbol" field.
func (u *DailyBarUpsert) SetSymbol(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldSymbol, v)
	return u
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateSymbol() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldSymbol)
	return u
}

// SetIsin sets the "isin" field.
func (u *DailyBarUpsert) SetIsin(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldIsin, v)
	return u
}

// UpdateIsin sets the "isin" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateIsin() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldIsin)
	return u
}

// SetName sets the "name" field.
func (u *DailyBarUpsert) SetName(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateName() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldName)
	return u
}

// SetTradingDate sets the "trading_date" field.
func (u *DailyBarUpsert) SetTradingDate(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldTradingDate, v)
	return u
}

// UpdateTradingDate sets the "trading_date" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateTradingDate() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldTradingDate)
	return u
}

// SetCurrency sets the "currency" field.
func (u *DailyBarUpsert) SetCurrency(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateCurrency() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldCurrency)
	return u
}

// SetOpeningPrice sets the "opening_price" field.
func (u *DailyBarUpsert) SetOpeningPrice(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldOpeningPrice, v)
	return u
}

// UpdateOpeningPrice sets the "opening_price" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateOpeningPrice() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldOpeningPrice)
	return u
}

// SetHighestPrice sets the "highest_price" field.
func (u *DailyBarUpsert) SetHighestPrice(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldHighestPrice, v)
	return u
}

// UpdateHighestPrice sets the "highest_price" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateHighestPrice() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldHighestPrice)
	return u
}

// SetLowestPrice sets the "lowest_price" field.
func (u *DailyBarUpsert) SetLowestPrice(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldLowestPrice, v)
	return u
}

// UpdateLowestPrice sets the "lowest_price" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateLowestPrice() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldLowestPrice)
	return u
}

// SetClosingPrice sets the "closing_price" field.
func (u *DailyBarUpsert) SetClosingPrice(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldClosingPrice, v)
	return u
}

// UpdateClosingPrice sets the "closing_price" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateClosingPrice() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldClosingPrice)
	return u
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (u *DailyBarUpsert) SetPriceChangeFromPreviousClose(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldPriceChangeFromPreviousClose, v)
	return u
}

// UpdatePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdatePriceChangeFromPreviousClose() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldPriceChangeFromPreviousClose)
	return u
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (u *DailyBarUpsert) SetPriceChangeRateFromPreviousClose(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldPriceChangeRateFromPreviousClose, v)
	return u
}

// UpdatePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdatePriceChangeRateFromPreviousClose() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldPriceChangeRateFromPreviousClose)
	return u
}

// SetTradedVolume sets the "traded_volume" field.
func (u *DailyBarUpsert) SetTradedVolume(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldTradedVolume, v)
	return u
}

// UpdateTradedVolume sets the "traded_volume" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateTradedVolume() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldTradedVolume)
	return u
}

// SetTradedAmount sets the "traded_amount" field.
func (u *DailyBarUpsert) SetTradedAmount(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldTradedAmount, v)
	return u
}

// UpdateTradedAmount sets the "traded_amount" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateTradedAmount() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldTradedAmount)
	return u
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (u *DailyBarUpsert) SetMarketCapitalization(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldMarketCapitalization, v)
	return u
}

// UpdateMarketCapitalization sets the "market_capitalization" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateMarketCapitalization() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldMarketCapitalization)
	return u
}

// SetExtensionsJSON sets the "extensions_json" field.
func (u *DailyBarUpsert) SetExtensionsJSON(v string) *DailyBarUpsert {
	u.Set(dailybar.FieldExtensionsJSON, v)
	return u
}

// UpdateExtensionsJSON sets the "extensions_json" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateExtensionsJSON() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldExtensionsJSON)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyBarUpsert) SetUpdatedAt(v time.Time) *DailyBarUpsert {
	u.Set(dailybar.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyBarUpsert) UpdateUpdatedAt() *DailyBarUpsert {
	u.SetExcluded(dailybar.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyBarUpsertOne) UpdateNewValues() *DailyBarUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dailybar.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DailyBarUpsertOne) Ignore() *DailyBarUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyBarUpsertOne) DoNothing() *DailyBarUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyBarCreate.OnConflict
// documentation for more info.
func (u *DailyBarUpsertOne) Update(set func(*DailyBarUpsert)) *DailyBarUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyBarUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *DailyBarUpsertOne) SetProvider(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateProvider() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderGroup sets the "provider_group" field.
func (u *DailyBarUpsertOne) SetProviderGroup(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetProviderGroup(v)
	})
}

// UpdateProviderGroup sets the "provider_group" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateProviderGroup() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateProviderGroup()
	})
}

// SetOperation sets the "operation" field.
func (u *DailyBarUpsertOne) SetOperation(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateOperation() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateOperation()
	})
}

// SetMarket sets the "market" field.
func (u *DailyBarUpsertOne) SetMarket(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetMarket(v)
	})
}

// UpdateMarket sets the "market" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateMarket() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateMarket()
	})
}

// SetSecurityType sets the "security_type" field.
func (u *DailyBarUpsertOne) SetSecurityType(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetSecurityType(v)
	})
}

// UpdateSecurityType sets the "security_type" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateSecurityType() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateSecurityType()
	})
}

// SetSymbol sets the "symbol" field.
func (u *DailyBarUpsertOne) SetSymbol(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateSymbol() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateSymbol()
	})
}

// SetIsin sets the "isin" field.
func (u *DailyBarUpsertOne) SetIsin(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetIsin(v)
	})
}

// UpdateIsin sets the "isin" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateIsin() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateIsin()
	})
}

// SetName sets the "name" field.
func (u *DailyBarUpsertOne) SetName(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateName() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateName()
	})
}

// SetTradingDate sets the "trading_date" field.
func (u *DailyBarUpsertOne) SetTradingDate(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradingDate(v)
	})
}

// UpdateTradingDate sets the "trading_date" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateTradingDate() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradingDate()
	})
}

// SetCurrency sets the "currency" field.
func (u *DailyBarUpsertOne) SetCurrency(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateCurrency() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateCurrency()
	})
}

// SetOpeningPrice sets the "opening_price" field.
func (u *DailyBarUpsertOne) SetOpeningPrice(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetOpeningPrice(v)
	})
}

// UpdateOpeningPrice sets the "opening_price" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateOpeningPrice() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateOpeningPrice()
	})
}

// SetHighestPrice sets the "highest_price" field.
func (u *DailyBarUpsertOne) SetHighestPrice(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetHighestPrice(v)
	})
}

// UpdateHighestPrice sets the "highest_price" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateHighestPrice() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateHighestPrice()
	})
}

// SetLowestPrice sets the "lowest_price" field.
func (u *DailyBarUpsertOne) SetLowestPrice(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetLowestPrice(v)
	})
}

// UpdateLowestPrice sets the "lowest_price" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateLowestPrice() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateLowestPrice()
	})
}

// SetClosingPrice sets the "closing_price" field.
func (u *DailyBarUpsertOne) SetClosingPrice(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetClosingPrice(v)
	})
}

// UpdateClosingPrice sets the "closing_price" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateClosingPrice() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateClosingPrice()
	})
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (u *DailyBarUpsertOne) SetPriceChangeFromPreviousClose(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetPriceChangeFromPreviousClose(v)
	})
}

// UpdatePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdatePriceChangeFromPreviousClose() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdatePriceChangeFromPreviousClose()
	})
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (u *DailyBarUpsertOne) SetPriceChangeRateFromPreviousClose(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetPriceChangeRateFromPreviousClose(v)
	})
}

// UpdatePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdatePriceChangeRateFromPreviousClose() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdatePriceChangeRateFromPreviousClose()
	})
}

// SetTradedVolume sets the "traded_volume" field.
func (u *DailyBarUpsertOne) SetTradedVolume(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradedVolume(v)
	})
}

// UpdateTradedVolume sets the "traded_volume" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateTradedVolume() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradedVolume()
	})
}

// SetTradedAmount sets the "traded_amount" field.
func (u *DailyBarUpsertOne) SetTradedAmount(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradedAmount(v)
	})
}

// UpdateTradedAmount sets the "traded_amount" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateTradedAmount() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradedAmount()
	})
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (u *DailyBarUpsertOne) SetMarketCapitalization(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetMarketCapitalization(v)
	})
}

// UpdateMarketCapitalization sets the "market_capitalization" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateMarketCapitalization() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateMarketCapitalization()
	})
}

// SetExtensionsJSON sets the "extensions_json" field.
func (u *DailyBarUpsertOne) SetExtensionsJSON(v string) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetExtensionsJSON(v)
	})
}

// UpdateExtensionsJSON sets the "extensions_json" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateExtensionsJSON() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateExtensionsJSON()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyBarUpsertOne) SetUpdatedAt(v time.Time) *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyBarUpsertOne) UpdateUpdatedAt() *DailyBarUpsertOne {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DailyBarUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyBarCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyBarUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DailyBarUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DailyBarUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DailyBarCreateBulk is the builder for creating many DailyBar entities in bulk.
type DailyBarCreateBulk struct {
	config
	err      error
	builders []*DailyBarCreate
	conflict []sql.ConflictOption
}

// Save creates the DailyBar entities in the database.
func (_c *DailyBarCreateBulk) Save(ctx context.Context) ([]*DailyBar, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyBar, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyBarMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyBarCreateBulk) SaveX(ctx context.Context) []*DailyBar {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyBarCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyBarCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyBar.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyBarUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyBarCreateBulk) OnConflict(opts ...sql.ConflictOption) *DailyBarUpsertBulk {
	_c.conflict = opts
	return &DailyBarUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyBarCreateBulk) OnConflictColumns(columns ...string) *DailyBarUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyBarUpsertBulk{
		create: _c,
	}
}

// DailyBarUpsertBulk is the builder for "upsert"-ing
// a bulk of DailyBar nodes.
type DailyBarUpsertBulk struct {
	create *DailyBarCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyBarUpsertBulk) UpdateNewValues() *DailyBarUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dailybar.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyBar.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DailyBarUpsertBulk) Ignore() *DailyBarUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyBarUpsertBulk) DoNothing() *DailyBarUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyBarCreateBulk.OnConflict
// documentation for more info.
func (u *DailyBarUpsertBulk) Update(set func(*DailyBarUpsert)) *DailyBarUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyBarUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *DailyBarUpsertBulk) SetProvider(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateProvider() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderGroup sets the "provider_group" field.
func (u *DailyBarUpsertBulk) SetProviderGroup(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetProviderGroup(v)
	})
}

// UpdateProviderGroup sets the "provider_group" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateProviderGroup() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateProviderGroup()
	})
}

// SetOperation sets the "operation" field.
func (u *DailyBarUpsertBulk) SetOperation(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateOperation() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateOperation()
	})
}

// SetMarket sets the "market" field.
func (u *DailyBarUpsertBulk) SetMarket(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetMarket(v)
	})
}

// UpdateMarket sets the "market" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateMarket() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateMarket()
	})
}

// SetSecurityType sets the "security_type" field.
func (u *DailyBarUpsertBulk) SetSecurityType(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetSecurityType(v)
	})
}

// UpdateSecurityType sets the "security_type" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateSecurityType() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateSecurityType()
	})
}

// SetSymbol sets the "symbol" field.
func (u *DailyBarUpsertBulk) SetSymbol(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateSymbol() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateSymbol()
	})
}

// SetIsin sets the "isin" field.
func (u *DailyBarUpsertBulk) SetIsin(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetIsin(v)
	})
}

// UpdateIsin sets the "isin" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateIsin() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateIsin()
	})
}

// SetName sets the "name" field.
func (u *DailyBarUpsertBulk) SetName(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateName() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateName()
	})
}

// SetTradingDate sets the "trading_date" field.
func (u *DailyBarUpsertBulk) SetTradingDate(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradingDate(v)
	})
}

// UpdateTradingDate sets the "trading_date" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateTradingDate() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradingDate()
	})
}

// SetCurrency sets the "currency" field.
func (u *DailyBarUpsertBulk) SetCurrency(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateCurrency() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateCurrency()
	})
}

// SetOpeningPrice sets the "opening_price" field.
func (u *DailyBarUpsertBulk) SetOpeningPrice(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetOpeningPrice(v)
	})
}

// UpdateOpeningPrice sets the "opening_price" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateOpeningPrice() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateOpeningPrice()
	})
}

// SetHighestPrice sets the "highest_price" field.
func (u *DailyBarUpsertBulk) SetHighestPrice(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetHighestPrice(v)
	})
}

// UpdateHighestPrice sets the "highest_price" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateHighestPrice() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateHighestPrice()
	})
}

// SetLowestPrice sets the "lowest_price" field.
func (u *DailyBarUpsertBulk) SetLowestPrice(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetLowestPrice(v)
	})
}

// UpdateLowestPrice sets the "lowest_price" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateLowestPrice() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateLowestPrice()
	})
}

// SetClosingPrice sets the "closing_price" field.
func (u *DailyBarUpsertBulk) SetClosingPrice(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetClosingPrice(v)
	})
}

// UpdateClosingPrice sets the "closing_price" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateClosingPrice() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateClosingPrice()
	})
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (u *DailyBarUpsertBulk) SetPriceChangeFromPreviousClose(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetPriceChangeFromPreviousClose(v)
	})
}

// UpdatePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdatePriceChangeFromPreviousClose() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdatePriceChangeFromPreviousClose()
	})
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (u *DailyBarUpsertBulk) SetPriceChangeRateFromPreviousClose(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetPriceChangeRateFromPreviousClose(v)
	})
}

// UpdatePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdatePriceChangeRateFromPreviousClose() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdatePriceChangeRateFromPreviousClose()
	})
}

// SetTradedVolume sets the "traded_volume" field.
func (u *DailyBarUpsertBulk) SetTradedVolume(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradedVolume(v)
	})
}

// UpdateTradedVolume sets the "traded_volume" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateTradedVolume() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradedVolume()
	})
}

// SetTradedAmount sets the "traded_amount" field.
func (u *DailyBarUpsertBulk) SetTradedAmount(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetTradedAmount(v)
	})
}

// UpdateTradedAmount sets the "traded_amount" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateTradedAmount() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateTradedAmount()
	})
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (u *DailyBarUpsertBulk) SetMarketCapitalization(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetMarketCapitalization(v)
	})
}

// UpdateMarketCapitalization sets the "market_capitalization" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateMarketCapitalization() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateMarketCapitalization()
	})
}

// SetExtensionsJSON sets the "extensions_json" field.
func (u *DailyBarUpsertBulk) SetExtensionsJSON(v string) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetExtensionsJSON(v)
	})
}

// UpdateExtensionsJSON sets the "extensions_json" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateExtensionsJSON() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateExtensionsJSON()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyBarUpsertBulk) SetUpdatedAt(v time.Time) *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyBarUpsertBulk) UpdateUpdatedAt() *DailyBarUpsertBulk {
	return u.Update(func(s *DailyBarUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DailyBarUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DailyBarCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyBarCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyBarUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
