// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/dailybar"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/predicate"
)

// DailyBarUpdate is the builder for updating DailyBar entities.
type DailyBarUpdate struct {
	config
	hooks    []Hook
	mutation *DailyBarMutation
}

// Where appends a list predicates to the DailyBarUpdate builder.
func (_u *DailyBarUpdate) Where(ps ...predicate.DailyBar) *DailyBarUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *DailyBarUpdate) SetProvider(v string) *DailyBarUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableProvider(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderGroup sets the "provider_group" field.
func (_u *DailyBarUpdate) SetProviderGroup(v string) *DailyBarUpdate {
	_u.mutation.SetProviderGroup(v)
	return _u
}

// SetNillableProviderGroup sets the "provider_group" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableProviderGroup(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetProviderGroup(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *DailyBarUpdate) SetOperation(v string) *DailyBarUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableOperation(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetMarket sets the "market" field.
func (_u *DailyBarUpdate) SetMarket(v string) *DailyBarUpdate {
	_u.mutation.SetMarket(v)
	return _u
}

// SetNillableMarket sets the "market" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableMarket(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetMarket(*v)
	}
	return _u
}

// SetSecurityType sets the "security_type" field.
func (_u *DailyBarUpdate) SetSecurityType(v string) *DailyBarUpdate {
	_u.mutation.SetSecurityType(v)
	return _u
}

// SetNillableSecurityType sets the "security_type" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableSecurityType(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetSecurityType(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *DailyBarUpdate) SetSymbol(v string) *DailyBarUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableSymbol(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetIsin sets the "isin" field.
func (_u *DailyBarUpdate) SetIsin(v string) *DailyBarUpdate {
	_u.mutation.SetIsin(v)
	return _u
}

// SetNillableIsin sets the "isin" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableIsin(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetIsin(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DailyBarUpdate) SetName(v string) *DailyBarUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableName(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTradingDate sets the "trading_date" field.
func (_u *DailyBarUpdate) SetTradingDate(v string) *DailyBarUpdate {
	_u.mutation.SetTradingDate(v)
	return _u
}

// SetNillableTradingDate sets the "trading_date" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableTradingDate(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetTradingDate(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DailyBarUpdate) SetCurrency(v string) *DailyBarUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableCurrency(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOpeningPrice sets the "opening_price" field.
func (_u *DailyBarUpdate) SetOpeningPrice(v string) *DailyBarUpdate {
	_u.mutation.SetOpeningPrice(v)
	return _u
}

// SetNillableOpeningPrice sets the "opening_price" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableOpeningPrice(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetOpeningPrice(*v)
	}
	return _u
}

// SetHighestPrice sets the "highest_price" field.
func (_u *DailyBarUpdate) SetHighestPrice(v string) *DailyBarUpdate {
	_u.mutation.SetHighestPrice(v)
	return _u
}

// SetNillableHighestPrice sets the "highest_price" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableHighestPrice(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetHighestPrice(*v)
	}
	return _u
}

// SetLowestPrice sets the "lowest_price" field.
func (_u *DailyBarUpdate) SetLowestPrice(v string) *DailyBarUpdate {
	_u.mutation.SetLowestPrice(v)
	return _u
}

// SetNillableLowestPrice sets the "lowest_price" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableLowestPrice(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetLowestPrice(*v)
	}
	return _u
}

// SetClosingPrice sets the "closing_price" field.
func (_u *DailyBarUpdate) SetClosingPrice(v string) *DailyBarUpdate {
	_u.mutation.SetClosingPrice(v)
	return _u
}

// SetNillableClosingPrice sets the "closing_price" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableClosingPrice(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetClosingPrice(*v)
	}
	return _u
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (_u *DailyBarUpdate) SetPriceChangeFromPreviousClose(v string) *DailyBarUpdate {
	_u.mutation.SetPriceChangeFromPreviousClose(v)
	return _u
}

// SetNillablePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillablePriceChangeFromPreviousClose(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetPriceChangeFromPreviousClose(*v)
	}
	return _u
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (_u *DailyBarUpdate) SetPriceChangeRateFromPreviousClose(v string) *DailyBarUpdate {
	_u.mutation.SetPriceChangeRateFromPreviousClose(v)
	return _u
}

// SetNillablePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillablePriceChangeRateFromPreviousClose(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetPriceChangeRateFromPreviousClose(*v)
	}
	return _u
}

// SetTradedVolume sets the "traded_volume" field.
func (_u *DailyBarUpdate) SetTradedVolume(v string) *DailyBarUpdate {
	_u.mutation.SetTradedVolume(v)
	return _u
}

// SetNillableTradedVolume sets the "traded_volume" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableTradedVolume(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetTradedVolume(*v)
	}
	return _u
}

// SetTradedAmount sets the "traded_amount" field.
func (_u *DailyBarUpdate) SetTradedAmount(v string) *DailyBarUpdate {
	_u.mutation.SetTradedAmount(v)
	return _u
}

// SetNillableTradedAmount sets the "traded_amount" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableTradedAmount(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetTradedAmount(*v)
	}
	return _u
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (_u *DailyBarUpdate) SetMarketCapitalization(v string) *DailyBarUpdate {
	_u.mutation.SetMarketCapitalization(v)
	return _u
}

// SetNillableMarketCapitalization sets the "market_capitalization" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableMarketCapitalization(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetMarketCapitalization(*v)
	}
	return _u
}

// SetExtensionsJSON sets the "extensions_json" field.
func (_u *DailyBarUpdate) SetExtensionsJSON(v string) *DailyBarUpdate {
	_u.mutation.SetExtensionsJSON(v)
	return _u
}

// SetNillableExtensionsJSON sets the "extensions_json" field if the given value is not nil.
func (_u *DailyBarUpdate) SetNillableExtensionsJSON(v *string) *DailyBarUpdate {
	if v != nil {
		_u.SetExtensionsJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyBarUpdate) SetUpdatedAt(v time.Time) *DailyBarUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DailyBarMutation object of the builder.
func (_u *DailyBarUpdate) Mutation() *DailyBarMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyBarUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyBarUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyBarUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyBarUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyBarUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailybar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyBarUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := dailybar.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderGroup(); ok {
		if err := dailybar.ProviderGroupValidator(v); err != nil {
			return &ValidationError{Name: "provider_group", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := dailybar.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "DailyBar.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Market(); ok {
		if err := dailybar.MarketValidator(v); err != nil {
			return &ValidationError{Name: "market", err: fmt.Errorf(`ent: validator failed for field "DailyBar.market": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecurityType(); ok {
		if err := dailybar.SecurityTypeValidator(v); err != nil {
			return &ValidationError{Name: "security_type", err: fmt.Errorf(`ent: validator failed for field "DailyBar.security_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := dailybar.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "DailyBar.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradingDate(); ok {
		if err := dailybar.TradingDateValidator(v); err != nil {
			return &ValidationError{Name: "trading_date", err: fmt.Errorf(`ent: validator failed for field "DailyBar.trading_date": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyBarUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailybar.Table, dailybar.Columns, sqlgraph.NewFieldSpec(dailybar.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(dailybar.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderGroup(); ok {
		_spec.SetField(dailybar.FieldProviderGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(dailybar.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Market(); ok {
		_spec.SetField(dailybar.FieldMarket, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecurityType(); ok {
		_spec.SetField(dailybar.FieldSecurityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(dailybar.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isin(); ok {
		_spec.SetField(dailybar.FieldIsin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dailybar.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradingDate(); ok {
		_spec.SetField(dailybar.FieldTradingDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(dailybar.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpeningPrice(); ok {
		_spec.SetField(dailybar.FieldOpeningPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.HighestPrice(); ok {
		_spec.SetField(dailybar.FieldHighestPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.LowestPrice(); ok {
		_spec.SetField(dailybar.FieldLowestPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosingPrice(); ok {
		_spec.SetField(dailybar.FieldClosingPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceChangeFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeFromPreviousClose, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceChangeRateFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeRateFromPreviousClose, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradedVolume(); ok {
		_spec.SetField(dailybar.FieldTradedVolume, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradedAmount(); ok {
		_spec.SetField(dailybar.FieldTradedAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketCapitalization(); ok {
		_spec.SetField(dailybar.FieldMarketCapitalization, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtensionsJSON(); ok {
		_spec.SetField(dailybar.FieldExtensionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailybar.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailybar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyBarUpdateOne is the builder for updating a single DailyBar entity.
type DailyBarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyBarMutation
}

// SetProvider sets the "provider" field.
func (_u *DailyBarUpdateOne) SetProvider(v string) *DailyBarUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableProvider(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderGroup sets the "provider_group" field.
func (_u *DailyBarUpdateOne) SetProviderGroup(v string) *DailyBarUpdateOne {
	_u.mutation.SetProviderGroup(v)
	return _u
}

// SetNillableProviderGroup sets the "provider_group" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableProviderGroup(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetProviderGroup(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *DailyBarUpdateOne) SetOperation(v string) *DailyBarUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableOperation(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetMarket sets the "market" field.
func (_u *DailyBarUpdateOne) SetMarket(v string) *DailyBarUpdateOne {
	_u.mutation.SetMarket(v)
	return _u
}

// SetNillableMarket sets the "market" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableMarket(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetMarket(*v)
	}
	return _u
}

// SetSecurityType sets the "security_type" field.
func (_u *DailyBarUpdateOne) SetSecurityType(v string) *DailyBarUpdateOne {
	_u.mutation.SetSecurityType(v)
	return _u
}

// SetNillableSecurityType sets the "security_type" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableSecurityType(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetSecurityType(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *DailyBarUpdateOne) SetSymbol(v string) *DailyBarUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableSymbol(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetIsin sets the "isin" field.
func (_u *DailyBarUpdateOne) SetIsin(v string) *DailyBarUpdateOne {
	_u.mutation.SetIsin(v)
	return _u
}

// SetNillableIsin sets the "isin" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableIsin(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetIsin(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DailyBarUpdateOne) SetName(v string) *DailyBarUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableName(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTradingDate sets the "trading_date" field.
func (_u *DailyBarUpdateOne) SetTradingDate(v string) *DailyBarUpdateOne {
	_u.mutation.SetTradingDate(v)
	return _u
}

// SetNillableTradingDate sets the "trading_date" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableTradingDate(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetTradingDate(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DailyBarUpdateOne) SetCurrency(v string) *DailyBarUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableCurrency(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOpeningPrice sets the "opening_price" field.
func (_u *DailyBarUpdateOne) SetOpeningPrice(v string) *DailyBarUpdateOne {
	_u.mutation.SetOpeningPrice(v)
	return _u
}

// SetNillableOpeningPrice sets the "opening_price" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableOpeningPrice(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetOpeningPrice(*v)
	}
	return _u
}

// SetHighestPrice sets the "highest_price" field.
func (_u *DailyBarUpdateOne) SetHighestPrice(v string) *DailyBarUpdateOne {
	_u.mutation.SetHighestPrice(v)
	return _u
}

// SetNillableHighestPrice sets the "highest_price" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableHighestPrice(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetHighestPrice(*v)
	}
	return _u
}

// SetLowestPrice sets the "lowest_price" field.
func (_u *DailyBarUpdateOne) SetLowestPrice(v string) *DailyBarUpdateOne {
	_u.mutation.SetLowestPrice(v)
	return _u
}

// SetNillableLowestPrice sets the "lowest_price" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableLowestPrice(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetLowestPrice(*v)
	}
	return _u
}

// SetClosingPrice sets the "closing_price" field.
func (_u *DailyBarUpdateOne) SetClosingPrice(v string) *DailyBarUpdateOne {
	_u.mutation.SetClosingPrice(v)
	return _u
}

// SetNillableClosingPrice sets the "closing_price" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableClosingPrice(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetClosingPrice(*v)
	}
	return _u
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (_u *DailyBarUpdateOne) SetPriceChangeFromPreviousClose(v string) *DailyBarUpdateOne {
	_u.mutation.SetPriceChangeFromPreviousClose(v)
	return _u
}

// SetNillablePriceChangeFromPreviousClose sets the "price_change_from_previous_close" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillablePriceChangeFromPreviousClose(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetPriceChangeFromPreviousClose(*v)
	}
	return _u
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (_u *DailyBarUpdateOne) SetPriceChangeRateFromPreviousClose(v string) *DailyBarUpdateOne {
	_u.mutation.SetPriceChangeRateFromPreviousClose(v)
	return _u
}

// SetNillablePriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillablePriceChangeRateFromPreviousClose(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetPriceChangeRateFromPreviousClose(*v)
	}
	return _u
}

// SetTradedVolume sets the "traded_volume" field.
func (_u *DailyBarUpdateOne) SetTradedVolume(v string) *DailyBarUpdateOne {
	_u.mutation.SetTradedVolume(v)
	return _u
}

// SetNillableTradedVolume sets the "traded_volume" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableTradedVolume(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetTradedVolume(*v)
	}
	return _u
}

// SetTradedAmount sets the "traded_amount" field.
func (_u *DailyBarUpdateOne) SetTradedAmount(v string) *DailyBarUpdateOne {
	_u.mutation.SetTradedAmount(v)
	return _u
}

// SetNillableTradedAmount sets the "traded_amount" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableTradedAmount(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetTradedAmount(*v)
	}
	return _u
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (_u *DailyBarUpdateOne) SetMarketCapitalization(v string) *DailyBarUpdateOne {
	_u.mutation.SetMarketCapitalization(v)
	return _u
}

// SetNillableMarketCapitalization sets the "market_capitalization" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableMarketCapitalization(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetMarketCapitalization(*v)
	}
	return _u
}

// SetExtensionsJSON sets the "extensions_json" field.
func (_u *DailyBarUpdateOne) SetExtensionsJSON(v string) *DailyBarUpdateOne {
	_u.mutation.SetExtensionsJSON(v)
	return _u
}

// SetNillableExtensionsJSON sets the "extensions_json" field if the given value is not nil.
func (_u *DailyBarUpdateOne) SetNillableExtensionsJSON(v *string) *DailyBarUpdateOne {
	if v != nil {
		_u.SetExtensionsJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyBarUpdateOne) SetUpdatedAt(v time.Time) *DailyBarUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DailyBarMutation object of the builder.
func (_u *DailyBarUpdateOne) Mutation() *DailyBarMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyBarUpdate builder.
func (_u *DailyBarUpdateOne) Where(ps ...predicate.DailyBar) *DailyBarUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyBarUpdateOne) Select(field string, fields ...string) *DailyBarUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyBar entity.
func (_u *DailyBarUpdateOne) Save(ctx context.Context) (*DailyBar, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyBarUpdateOne) SaveX(ctx context.Context) *DailyBar {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyBarUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyBarUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyBarUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailybar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyBarUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := dailybar.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderGroup(); ok {
		if err := dailybar.ProviderGroupValidator(v); err != nil {
			return &ValidationError{Name: "provider_group", err: fmt.Errorf(`ent: validator failed for field "DailyBar.provider_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := dailybar.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "DailyBar.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Market(); ok {
		if err := dailybar.MarketValidator(v); err != nil {
			return &ValidationError{Name: "market", err: fmt.Errorf(`ent: validator failed for field "DailyBar.market": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecurityType(); ok {
		if err := dailybar.SecurityTypeValidator(v); err != nil {
			return &ValidationError{Name: "security_type", err: fmt.Errorf(`ent: validator failed for field "DailyBar.security_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := dailybar.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "DailyBar.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradingDate(); ok {
		if err := dailybar.TradingDateValidator(v); err != nil {
			return &ValidationError{Name: "trading_date", err: fmt.Errorf(`ent: validator failed for field "DailyBar.trading_date": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyBarUpdateOne) sqlSave(ctx context.Context) (_node *DailyBar, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailybar.Table, dailybar.Columns, sqlgraph.NewFieldSpec(dailybar.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyBar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailybar.FieldID)
		for _, f := range fields {
			if !dailybar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailybar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(dailybar.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderGroup(); ok {
		_spec.SetField(dailybar.FieldProviderGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(dailybar.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Market(); ok {
		_spec.SetField(dailybar.FieldMarket, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecurityType(); ok {
		_spec.SetField(dailybar.FieldSecurityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(dailybar.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Isin(); ok {
		_spec.SetField(dailybar.FieldIsin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dailybar.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradingDate(); ok {
		_spec.SetField(dailybar.FieldTradingDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(dailybar.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpeningPrice(); ok {
		_spec.SetField(dailybar.FieldOpeningPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.HighestPrice(); ok {
		_spec.SetField(dailybar.FieldHighestPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.LowestPrice(); ok {
		_spec.SetField(dailybar.FieldLowestPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClosingPrice(); ok {
		_spec.SetField(dailybar.FieldClosingPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceChangeFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeFromPreviousClose, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceChangeRateFromPreviousClose(); ok {
		_spec.SetField(dailybar.FieldPriceChangeRateFromPreviousClose, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradedVolume(); ok {
		_spec.SetField(dailybar.FieldTradedVolume, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradedAmount(); ok {
		_spec.SetField(dailybar.FieldTradedAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketCapitalization(); ok {
		_spec.SetField(dailybar.FieldMarketCapitalization, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtensionsJSON(); ok {
		_spec.SetField(dailybar.FieldExtensionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailybar.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DailyBar{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailybar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
