// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/dailybar"
)

// DailyBar is the model entity for the DailyBar schema.
type DailyBar struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderGroup holds the value of the "provider_group" field.
	ProviderGroup string `json:"provider_group,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// Market holds the value of the "market" field.
	Market string `json:"market,omitempty"`
	// SecurityType holds the value of the "security_type" field.
	SecurityType string `json:"security_type,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// Isin holds the value of the "isin" field.
	Isin string `json:"isin,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TradingDate holds the value of the "trading_date" field.
	TradingDate string `json:"trading_date,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// OpeningPrice holds the value of the "opening_price" field.
	OpeningPrice string `json:"opening_price,omitempty"`
	// HighestPrice holds the value of the "highest_price" field.
	HighestPrice string `json:"highest_price,omitempty"`
	// LowestPrice holds the value of the "lowest_price" field.
	LowestPrice string `json:"lowest_price,omitempty"`
	// ClosingPrice holds the value of the "closing_price" field.
	ClosingPrice string `json:"closing_price,omitempty"`
	// PriceChangeFromPreviousClose holds the value of the "price_change_from_previous_close" field.
	PriceChangeFromPreviousClose string `json:"price_change_from_previous_close,omitempty"`
	// PriceChangeRateFromPreviousClose holds the value of the "price_change_rate_from_previous_close" field.
	PriceChangeRateFromPreviousClose string `json:"price_change_rate_from_previous_close,omitempty"`
	// TradedVolume holds the value of the "traded_volume" field.
	TradedVolume string `json:"traded_volume,omitempty"`
	// TradedAmount holds the value of the "traded_amount" field.
	TradedAmount string `json:"traded_amount,omitempty"`
	// MarketCapitalization holds the value of the "market_capitalization" field.
	MarketCapitalization string `json:"market_capitalization,omitempty"`
	// ExtensionsJSON holds the value of the "extensions_json" field.
	ExtensionsJSON string `json:"extensions_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyBar) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailybar.FieldID:
			values[i] = new(sql.NullInt64)
		case dailybar.FieldProvider, dailybar.FieldProviderGroup, dailybar.FieldOperation, dailybar.FieldMarket, dailybar.FieldSecurityType, dailybar.FieldSymbol, dailybar.FieldIsin, dailybar.FieldName, dailybar.FieldTradingDate, dailybar.FieldCurrency, dailybar.FieldOpeningPrice, dailybar.FieldHighestPrice, dailybar.FieldLowestPrice, dailybar.FieldClosingPrice, dailybar.FieldPriceChangeFromPreviousClose, dailybar.FieldPriceChangeRateFromPreviousClose, dailybar.FieldTradedVolume, dailybar.FieldTradedAmount, dailybar.FieldMarketCapitalization, dailybar.FieldExtensionsJSON:
			values[i] = new(sql.NullString)
		case dailybar.FieldCreatedAt, dailybar.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyBar fields.
func (_m *DailyBar) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailybar.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dailybar.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case dailybar.FieldProviderGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_group", values[i])
			} else if value.Valid {
				_m.ProviderGroup = value.String
			}
		case dailybar.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case dailybar.FieldMarket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field market", values[i])
			} else if value.Valid {
				_m.Market = value.String
			}
		case dailybar.FieldSecurityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field security_type", values[i])
			} else if value.Valid {
				_m.SecurityType = value.String
			}
		case dailybar.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case dailybar.FieldIsin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field isin", values[i])
			} else if value.Valid {
				_m.Isin = value.String
			}
		case dailybar.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case dailybar.FieldTradingDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trading_date", values[i])
			} else if value.Valid {
				_m.TradingDate = value.String
			}
		case dailybar.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case dailybar.FieldOpeningPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field opening_price", values[i])
			} else if value.Valid {
				_m.OpeningPrice = value.String
			}
		case dailybar.FieldHighestPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field highest_price", values[i])
			} else if value.Valid {
				_m.HighestPrice = value.String
			}
		case dailybar.FieldLowestPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lowest_price", values[i])
			} else if value.Valid {
				_m.LowestPrice = value.String
			}
		case dailybar.FieldClosingPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field closing_price", values[i])
			} else if value.Valid {
				_m.ClosingPrice = value.String
			}
		case dailybar.FieldPriceChangeFromPreviousClose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_change_from_previous_close", values[i])
			} else if value.Valid {
				_m.PriceChangeFromPreviousClose = value.String
			}
		case dailybar.FieldPriceChangeRateFromPreviousClose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_change_rate_from_previous_close", values[i])
			} else if value.Valid {
				_m.PriceChangeRateFromPreviousClose = value.String
			}
		case dailybar.FieldTradedVolume:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field traded_volume", values[i])
			} else if value.Valid {
				_m.TradedVolume = value.String
			}
		case dailybar.FieldTradedAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field traded_amount", values[i])
			} else if value.Valid {
				_m.TradedAmount = value.String
			}
		case dailybar.FieldMarketCapitalization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field market_capitalization", values[i])
			} else if value.Valid {
				_m.MarketCapitalization = value.String
			}
		case dailybar.FieldExtensionsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extensions_json", values[i])
			} else if value.Valid {
				_m.ExtensionsJSON = value.String
			}
		case dailybar.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dailybar.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyBar.
// This includes values selected through modifiers, order, etc.
func (_m *DailyBar) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DailyBar.
// Note that you need to call DailyBar.Unwrap() before calling this method if this DailyBar
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyBar) Update() *DailyBarUpdateOne {
	return NewDailyBarClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyBar entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyBar) Unwrap() *DailyBar {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyBar is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyBar) String() string {
	var builder strings.Builder
	builder.WriteString("DailyBar(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_group=")
	builder.WriteString(_m.ProviderGroup)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("market=")
	builder.WriteString(_m.Market)
	builder.WriteString(", ")
	builder.WriteString("security_type=")
	builder.WriteString(_m.SecurityType)
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	builder.WriteString("isin=")
	builder.WriteString(_m.Isin)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("trading_date=")
	builder.WriteString(_m.TradingDate)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("opening_price=")
	builder.WriteString(_m.OpeningPrice)
	builder.WriteString(", ")
	builder.WriteString("highest_price=")
	builder.WriteString(_m.HighestPrice)
	builder.WriteString(", ")
	builder.WriteString("lowest_price=")
	builder.WriteString(_m.LowestPrice)
	builder.WriteString(", ")
	builder.WriteString("closing_price=")
	builder.WriteString(_m.ClosingPrice)
	builder.WriteString(", ")
	builder.WriteString("price_change_from_previous_close=")
	builder.WriteString(_m.PriceChangeFromPreviousClose)
	builder.WriteString(", ")
	builder.WriteString("price_change_rate_from_previous_close=")
	builder.WriteString(_m.PriceChangeRateFromPreviousClose)
	builder.WriteString(", ")
	builder.WriteString("traded_volume=")
	builder.WriteString(_m.TradedVolume)
	builder.WriteString(", ")
	builder.WriteString("traded_amount=")
	builder.WriteString(_m.TradedAmount)
	builder.WriteString(", ")
	builder.WriteString("market_capitalization=")
	builder.WriteString(_m.MarketCapitalization)
	builder.WriteString(", ")
	builder.WriteString("extensions_json=")
	builder.WriteString(_m.ExtensionsJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DailyBars is a parsable slice of DailyBar.
type DailyBars []*DailyBar
