// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/dailybar"
	"github.com/ev3rlit/mwosa/storage/sqlite/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDailyBar = "DailyBar"
)

// DailyBarMutation represents an operation that mutates the DailyBar nodes in the graph.
type DailyBarMutation struct {
	config
	op                                    Op
	typ                                   string
	id                                    *int
	provider                              *string
	provider_group                        *string
	operation                             *string
	market                                *string
	security_type                         *string
	symbol                                *string
	isin                                  *string
	name                                  *string
	trading_date                          *string
	currency                              *string
	opening_price                         *string
	highest_price                         *string
	lowest_price                          *string
	closing_price                         *string
	price_change_from_previous_close      *string
	price_change_rate_from_previous_close *string
	traded_volume                         *string
	traded_amount                         *string
	market_capitalization                 *string
	extensions_json                       *string
	created_at                            *time.Time
	updated_at                            *time.Time
	clearedFields                         map[string]struct{}
	done                                  bool
	oldValue                              func(context.Context) (*DailyBar, error)
	predicates                            []predicate.DailyBar
}

var _ ent.Mutation = (*DailyBarMutation)(nil)

// dailybarOption allows management of the mutation configuration using functional options.
type dailybarOption func(*DailyBarMutation)

// newDailyBarMutation creates new mutation for the DailyBar entity.
func newDailyBarMutation(c config, op Op, opts ...dailybarOption) *DailyBarMutation {
	m := &DailyBarMutation{
		config:        c,
		op:            op,
		typ:           TypeDailyBar,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDailyBarID sets the ID field of the mutation.
func withDailyBarID(id int) dailybarOption {
	return func(m *DailyBarMutation) {
		var (
			err   error
			once  sync.Once
			value *DailyBar
		)
		m.oldValue = func(ctx context.Context) (*DailyBar, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DailyBar.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDailyBar sets the old DailyBar of the mutation.
func withDailyBar(node *DailyBar) dailybarOption {
	return func(m *DailyBarMutation) {
		m.oldValue = func(context.Context) (*DailyBar, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DailyBarMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DailyBarMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DailyBarMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DailyBarMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DailyBar.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetProvider sets the "provider" field.
func (m *DailyBarMutation) SetProvider(s string) {
	m.provider = &s
}

// Provider returns the value of the "provider" field in the mutation.
func (m *DailyBarMutation) Provider() (r string, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// OldProvider returns the old "provider" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldProvider(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvider: %w", err)
	}
	return oldValue.Provider, nil
}

// ResetProvider resets all changes to the "provider" field.
func (m *DailyBarMutation) ResetProvider() {
	m.provider = nil
}

// SetProviderGroup sets the "provider_group" field.
func (m *DailyBarMutation) SetProviderGroup(s string) {
	m.provider_group = &s
}

// ProviderGroup returns the value of the "provider_group" field in the mutation.
func (m *DailyBarMutation) ProviderGroup() (r string, exists bool) {
	v := m.provider_group
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderGroup returns the old "provider_group" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldProviderGroup(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderGroup is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderGroup requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderGroup: %w", err)
	}
	return oldValue.ProviderGroup, nil
}

// ResetProviderGroup resets all changes to the "provider_group" field.
func (m *DailyBarMutation) ResetProviderGroup() {
	m.provider_group = nil
}

// SetOperation sets the "operation" field.
func (m *DailyBarMutation) SetOperation(s string) {
	m.operation = &s
}

// Operation returns the value of the "operation" field in the mutation.
func (m *DailyBarMutation) Operation() (r string, exists bool) {
	v := m.operation
	if v == nil {
		return
	}
	return *v, true
}

// OldOperation returns the old "operation" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldOperation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOperation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOperation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOperation: %w", err)
	}
	return oldValue.Operation, nil
}

// ResetOperation resets all changes to the "operation" field.
func (m *DailyBarMutation) ResetOperation() {
	m.operation = nil
}

// SetMarket sets the "market" field.
func (m *DailyBarMutation) SetMarket(s string) {
	m.market = &s
}

// Market returns the value of the "market" field in the mutation.
func (m *DailyBarMutation) Market() (r string, exists bool) {
	v := m.market
	if v == nil {
		return
	}
	return *v, true
}

// OldMarket returns the old "market" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldMarket(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMarket is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMarket requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMarket: %w", err)
	}
	return oldValue.Market, nil
}

// ResetMarket resets all changes to the "market" field.
func (m *DailyBarMutation) ResetMarket() {
	m.market = nil
}

// SetSecurityType sets the "security_type" field.
func (m *DailyBarMutation) SetSecurityType(s string) {
	m.security_type = &s
}

// SecurityType returns the value of the "security_type" field in the mutation.
func (m *DailyBarMutation) SecurityType() (r string, exists bool) {
	v := m.security_type
	if v == nil {
		return
	}
	return *v, true
}

// OldSecurityType returns the old "security_type" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldSecurityType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSecurityType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSecurityType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSecurityType: %w", err)
	}
	return oldValue.SecurityType, nil
}

// ResetSecurityType resets all changes to the "security_type" field.
func (m *DailyBarMutation) ResetSecurityType() {
	m.security_type = nil
}

// SetSymbol sets the "symbol" field.
func (m *DailyBarMutation) SetSymbol(s string) {
	m.symbol = &s
}

// Symbol returns the value of the "symbol" field in the mutation.
func (m *DailyBarMutation) Symbol() (r string, exists bool) {
	v := m.symbol
	if v == nil {
		return
	}
	return *v, true
}

// OldSymbol returns the old "symbol" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldSymbol(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSymbol is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSymbol requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymbol: %w", err)
	}
	return oldValue.Symbol, nil
}

// ResetSymbol resets all changes to the "symbol" field.
func (m *DailyBarMutation) ResetSymbol() {
	m.symbol = nil
}

// SetIsin sets the "isin" field.
func (m *DailyBarMutation) SetIsin(s string) {
	m.isin = &s
}

// Isin returns the value of the "isin" field in the mutation.
func (m *DailyBarMutation) Isin() (r string, exists bool) {
	v := m.isin
	if v == nil {
		return
	}
	return *v, true
}

// OldIsin returns the old "isin" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldIsin(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsin: %w", err)
	}
	return oldValue.Isin, nil
}

// ResetIsin resets all changes to the "isin" field.
func (m *DailyBarMutation) ResetIsin() {
	m.isin = nil
}

// SetName sets the "name" field.
func (m *DailyBarMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DailyBarMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DailyBarMutation) ResetName() {
	m.name = nil
}

// SetTradingDate sets the "trading_date" field.
func (m *DailyBarMutation) SetTradingDate(s string) {
	m.trading_date = &s
}

// TradingDate returns the value of the "trading_date" field in the mutation.
func (m *DailyBarMutation) TradingDate() (r string, exists bool) {
	v := m.trading_date
	if v == nil {
		return
	}
	return *v, true
}

// OldTradingDate returns the old "trading_date" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldTradingDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTradingDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTradingDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTradingDate: %w", err)
	}
	return oldValue.TradingDate, nil
}

// ResetTradingDate resets all changes to the "trading_date" field.
func (m *DailyBarMutation) ResetTradingDate() {
	m.trading_date = nil
}

// SetCurrency sets the "currency" field.
func (m *DailyBarMutation) SetCurrency(s string) {
	m.currency = &s
}

// Currency returns the value of the "currency" field in the mutation.
func (m *DailyBarMutation) Currency() (r string, exists bool) {
	v := m.currency
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrency returns the old "currency" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldCurrency(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrency is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrency requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrency: %w", err)
	}
	return oldValue.Currency, nil
}

// ResetCurrency resets all changes to the "currency" field.
func (m *DailyBarMutation) ResetCurrency() {
	m.currency = nil
}

// SetOpeningPrice sets the "opening_price" field.
func (m *DailyBarMutation) SetOpeningPrice(s string) {
	m.opening_price = &s
}

// OpeningPrice returns the value of the "opening_price" field in the mutation.
func (m *DailyBarMutation) OpeningPrice() (r string, exists bool) {
	v := m.opening_price
	if v == nil {
		return
	}
	return *v, true
}

// OldOpeningPrice returns the old "opening_price" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldOpeningPrice(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpeningPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpeningPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpeningPrice: %w", err)
	}
	return oldValue.OpeningPrice, nil
}

// ResetOpeningPrice resets all changes to the "opening_price" field.
func (m *DailyBarMutation) ResetOpeningPrice() {
	m.opening_price = nil
}

// SetHighestPrice sets the "highest_price" field.
func (m *DailyBarMutation) SetHighestPrice(s string) {
	m.highest_price = &s
}

// HighestPrice returns the value of the "highest_price" field in the mutation.
func (m *DailyBarMutation) HighestPrice() (r string, exists bool) {
	v := m.highest_price
	if v == nil {
		return
	}
	return *v, true
}

// OldHighestPrice returns the old "highest_price" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldHighestPrice(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHighestPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHighestPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHighestPrice: %w", err)
	}
	return oldValue.HighestPrice, nil
}

// ResetHighestPrice resets all changes to the "highest_price" field.
func (m *DailyBarMutation) ResetHighestPrice() {
	m.highest_price = nil
}

// SetLowestPrice sets the "lowest_price" field.
func (m *DailyBarMutation) SetLowestPrice(s string) {
	m.lowest_price = &s
}

// LowestPrice returns the value of the "lowest_price" field in the mutation.
func (m *DailyBarMutation) LowestPrice() (r string, exists bool) {
	v := m.lowest_price
	if v == nil {
		return
	}
	return *v, true
}

// OldLowestPrice returns the old "lowest_price" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldLowestPrice(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLowestPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLowestPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLowestPrice: %w", err)
	}
	return oldValue.LowestPrice, nil
}

// ResetLowestPrice resets all changes to the "lowest_price" field.
func (m *DailyBarMutation) ResetLowestPrice() {
	m.lowest_price = nil
}

// SetClosingPrice sets the "closing_price" field.
func (m *DailyBarMutation) SetClosingPrice(s string) {
	m.closing_price = &s
}

// ClosingPrice returns the value of the "closing_price" field in the mutation.
func (m *DailyBarMutation) ClosingPrice() (r string, exists bool) {
	v := m.closing_price
	if v == nil {
		return
	}
	return *v, true
}

// OldClosingPrice returns the old "closing_price" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldClosingPrice(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClosingPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClosingPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClosingPrice: %w", err)
	}
	return oldValue.ClosingPrice, nil
}

// ResetClosingPrice resets all changes to the "closing_price" field.
func (m *DailyBarMutation) ResetClosingPrice() {
	m.closing_price = nil
}

// SetPriceChangeFromPreviousClose sets the "price_change_from_previous_close" field.
func (m *DailyBarMutation) SetPriceChangeFromPreviousClose(s string) {
	m.price_change_from_previous_close = &s
}

// PriceChangeFromPreviousClose returns the value of the "price_change_from_previous_close" field in the mutation.
func (m *DailyBarMutation) PriceChangeFromPreviousClose() (r string, exists bool) {
	v := m.price_change_from_previous_close
	if v == nil {
		return
	}
	return *v, true
}

// OldPriceChangeFromPreviousClose returns the old "price_change_from_previous_close" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldPriceChangeFromPreviousClose(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPriceChangeFromPreviousClose is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPriceChangeFromPreviousClose requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPriceChangeFromPreviousClose: %w", err)
	}
	return oldValue.PriceChangeFromPreviousClose, nil
}

// ResetPriceChangeFromPreviousClose resets all changes to the "price_change_from_previous_close" field.
func (m *DailyBarMutation) ResetPriceChangeFromPreviousClose() {
	m.price_change_from_previous_close = nil
}

// SetPriceChangeRateFromPreviousClose sets the "price_change_rate_from_previous_close" field.
func (m *DailyBarMutation) SetPriceChangeRateFromPreviousClose(s string) {
	m.price_change_rate_from_previous_close = &s
}

// PriceChangeRateFromPreviousClose returns the value of the "price_change_rate_from_previous_close" field in the mutation.
func (m *DailyBarMutation) PriceChangeRateFromPreviousClose() (r string, exists bool) {
	v := m.price_change_rate_from_previous_close
	if v == nil {
		return
	}
	return *v, true
}

// OldPriceChangeRateFromPreviousClose returns the old "price_change_rate_from_previous_close" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldPriceChangeRateFromPreviousClose(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPriceChangeRateFromPreviousClose is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPriceChangeRateFromPreviousClose requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPriceChangeRateFromPreviousClose: %w", err)
	}
	return oldValue.PriceChangeRateFromPreviousClose, nil
}

// ResetPriceChangeRateFromPreviousClose resets all changes to the "price_change_rate_from_previous_close" field.
func (m *DailyBarMutation) ResetPriceChangeRateFromPreviousClose() {
	m.price_change_rate_from_previous_close = nil
}

// SetTradedVolume sets the "traded_volume" field.
func (m *DailyBarMutation) SetTradedVolume(s string) {
	m.traded_volume = &s
}

// TradedVolume returns the value of the "traded_volume" field in the mutation.
func (m *DailyBarMutation) TradedVolume() (r string, exists bool) {
	v := m.traded_volume
	if v == nil {
		return
	}
	return *v, true
}

// OldTradedVolume returns the old "traded_volume" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldTradedVolume(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTradedVolume is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTradedVolume requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTradedVolume: %w", err)
	}
	return oldValue.TradedVolume, nil
}

// ResetTradedVolume resets all changes to the "traded_volume" field.
func (m *DailyBarMutation) ResetTradedVolume() {
	m.traded_volume = nil
}

// SetTradedAmount sets the "traded_amount" field.
func (m *DailyBarMutation) SetTradedAmount(s string) {
	m.traded_amount = &s
}

// TradedAmount returns the value of the "traded_amount" field in the mutation.
func (m *DailyBarMutation) TradedAmount() (r string, exists bool) {
	v := m.traded_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldTradedAmount returns the old "traded_amount" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldTradedAmount(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTradedAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTradedAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTradedAmount: %w", err)
	}
	return oldValue.TradedAmount, nil
}

// ResetTradedAmount resets all changes to the "traded_amount" field.
func (m *DailyBarMutation) ResetTradedAmount() {
	m.traded_amount = nil
}

// SetMarketCapitalization sets the "market_capitalization" field.
func (m *DailyBarMutation) SetMarketCapitalization(s string) {
	m.market_capitalization = &s
}

// MarketCapitalization returns the value of the "market_capitalization" field in the mutation.
func (m *DailyBarMutation) MarketCapitalization() (r string, exists bool) {
	v := m.market_capitalization
	if v == nil {
		return
	}
	return *v, true
}

// OldMarketCapitalization returns the old "market_capitalization" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldMarketCapitalization(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMarketCapitalization is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMarketCapitalization requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMarketCapitalization: %w", err)
	}
	return oldValue.MarketCapitalization, nil
}

// ResetMarketCapitalization resets all changes to the "market_capitalization" field.
func (m *DailyBarMutation) ResetMarketCapitalization() {
	m.market_capitalization = nil
}

// SetExtensionsJSON sets the "extensions_json" field.
func (m *DailyBarMutation) SetExtensionsJSON(s string) {
	m.extensions_json = &s
}

// ExtensionsJSON returns the value of the "extensions_json" field in the mutation.
func (m *DailyBarMutation) ExtensionsJSON() (r string, exists bool) {
	v := m.extensions_json
	if v == nil {
		return
	}
	return *v, true
}

// OldExtensionsJSON returns the old "extensions_json" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldExtensionsJSON(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExtensionsJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExtensionsJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExtensionsJSON: %w", err)
	}
	return oldValue.ExtensionsJSON, nil
}

// ResetExtensionsJSON resets all changes to the "extensions_json" field.
func (m *DailyBarMutation) ResetExtensionsJSON() {
	m.extensions_json = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DailyBarMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DailyBarMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DailyBarMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DailyBarMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DailyBarMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the DailyBar entity.
// If the DailyBar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DailyBarMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DailyBarMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the DailyBarMutation builder.
func (m *DailyBarMutation) Where(ps ...predicate.DailyBar) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DailyBarMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DailyBarMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DailyBar, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DailyBarMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DailyBarMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DailyBar).
func (m *DailyBarMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DailyBarMutation) Fields() []string {
	fields := make([]string, 0, 22)
	if m.provider != nil {
		fields = append(fields, dailybar.FieldProvider)
	}
	if m.provider_group != nil {
		fields = append(fields, dailybar.FieldProviderGroup)
	}
	if m.operation != nil {
		fields = append(fields, dailybar.FieldOperation)
	}
	if m.market != nil {
		fields = append(fields, dailybar.FieldMarket)
	}
	if m.security_type != nil {
		fields = append(fields, dailybar.FieldSecurityType)
	}
	if m.symbol != nil {
		fields = append(fields, dailybar.FieldSymbol)
	}
	if m.isin != nil {
		fields = append(fields, dailybar.FieldIsin)
	}
	if m.name != nil {
		fields = append(fields, dailybar.FieldName)
	}
	if m.trading_date != nil {
		fields = append(fields, dailybar.FieldTradingDate)
	}
	if m.currency != nil {
		fields = append(fields, dailybar.FieldCurrency)
	}
	if m.opening_price != nil {
		fields = append(fields, dailybar.FieldOpeningPrice)
	}
	if m.highest_price != nil {
		fields = append(fields, dailybar.FieldHighestPrice)
	}
	if m.lowest_price != nil {
		fields = append(fields, dailybar.FieldLowestPrice)
	}
	if m.closing_price != nil {
		fields = append(fields, dailybar.FieldClosingPrice)
	}
	if m.price_change_from_previous_close != nil {
		fields = append(fields, dailybar.FieldPriceChangeFromPreviousClose)
	}
	if m.price_change_rate_from_previous_close != nil {
		fields = append(fields, dailybar.FieldPriceChangeRateFromPreviousClose)
	}
	if m.traded_volume != nil {
		fields = append(fields, dailybar.FieldTradedVolume)
	}
	if m.traded_amount != nil {
		fields = append(fields, dailybar.FieldTradedAmount)
	}
	if m.market_capitalization != nil {
		fields = append(fields, dailybar.FieldMarketCapitalization)
	}
	if m.extensions_json != nil {
		fields = append(fields, dailybar.FieldExtensionsJSON)
	}
	if m.created_at != nil {
		fields = append(fields, dailybar.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, dailybar.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DailyBarMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dailybar.FieldProvider:
		return m.Provider()
	case dailybar.FieldProviderGroup:
		return m.ProviderGroup()
	case dailybar.FieldOperation:
		return m.Operation()
	case dailybar.FieldMarket:
		return m.Market()
	case dailybar.FieldSecurityType:
		return m.SecurityType()
	case dailybar.FieldSymbol:
		return m.Symbol()
	case dailybar.FieldIsin:
		return m.Isin()
	case dailybar.FieldName:
		return m.Name()
	case dailybar.FieldTradingDate:
		return m.TradingDate()
	case dailybar.FieldCurrency:
		return m.Currency()
	case dailybar.FieldOpeningPrice:
		return m.OpeningPrice()
	case dailybar.FieldHighestPrice:
		return m.HighestPrice()
	case dailybar.FieldLowestPrice:
		return m.LowestPrice()
	case dailybar.FieldClosingPrice:
		return m.ClosingPrice()
	case dailybar.FieldPriceChangeFromPreviousClose:
		return m.PriceChangeFromPreviousClose()
	case dailybar.FieldPriceChangeRateFromPreviousClose:
		return m.PriceChangeRateFromPreviousClose()
	case dailybar.FieldTradedVolume:
		return m.TradedVolume()
	case dailybar.FieldTradedAmount:
		return m.TradedAmount()
	case dailybar.FieldMarketCapitalization:
		return m.MarketCapitalization()
	case dailybar.FieldExtensionsJSON:
		return m.ExtensionsJSON()
	case dailybar.FieldCreatedAt:
		return m.CreatedAt()
	case dailybar.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DailyBarMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dailybar.FieldProvider:
		return m.OldProvider(ctx)
	case dailybar.FieldProviderGroup:
		return m.OldProviderGroup(ctx)
	case dailybar.FieldOperation:
		return m.OldOperation(ctx)
	case dailybar.FieldMarket:
		return m.OldMarket(ctx)
	case dailybar.FieldSecurityType:
		return m.OldSecurityType(ctx)
	case dailybar.FieldSymbol:
		return m.OldSymbol(ctx)
	case dailybar.FieldIsin:
		return m.OldIsin(ctx)
	case dailybar.FieldName:
		return m.OldName(ctx)
	case dailybar.FieldTradingDate:
		return m.OldTradingDate(ctx)
	case dailybar.FieldCurrency:
		return m.OldCurrency(ctx)
	case dailybar.FieldOpeningPrice:
		return m.OldOpeningPrice(ctx)
	case dailybar.FieldHighestPrice:
		return m.OldHighestPrice(ctx)
	case dailybar.FieldLowestPrice:
		return m.OldLowestPrice(ctx)
	case dailybar.FieldClosingPrice:
		return m.OldClosingPrice(ctx)
	case dailybar.FieldPriceChangeFromPreviousClose:
		return m.OldPriceChangeFromPreviousClose(ctx)
	case dailybar.FieldPriceChangeRateFromPreviousClose:
		return m.OldPriceChangeRateFromPreviousClose(ctx)
	case dailybar.FieldTradedVolume:
		return m.OldTradedVolume(ctx)
	case dailybar.FieldTradedAmount:
		return m.OldTradedAmount(ctx)
	case dailybar.FieldMarketCapitalization:
		return m.OldMarketCapitalization(ctx)
	case dailybar.FieldExtensionsJSON:
		return m.OldExtensionsJSON(ctx)
	case dailybar.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dailybar.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown DailyBar field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DailyBarMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dailybar.FieldProvider:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case dailybar.FieldProviderGroup:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderGroup(v)
		return nil
	case dailybar.FieldOperation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOperation(v)
		return nil
	case dailybar.FieldMarket:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMarket(v)
		return nil
	case dailybar.FieldSecurityType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSecurityType(v)
		return nil
	case dailybar.FieldSymbol:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymbol(v)
		return nil
	case dailybar.FieldIsin:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsin(v)
		return nil
	case dailybar.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case dailybar.FieldTradingDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTradingDate(v)
		return nil
	case dailybar.FieldCurrency:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrency(v)
		return nil
	case dailybar.FieldOpeningPrice:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpeningPrice(v)
		return nil
	case dailybar.FieldHighestPrice:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHighestPrice(v)
		return nil
	case dailybar.FieldLowestPrice:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLowestPrice(v)
		return nil
	case dailybar.FieldClosingPrice:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClosingPrice(v)
		return nil
	case dailybar.FieldPriceChangeFromPreviousClose:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPriceChangeFromPreviousClose(v)
		return nil
	case dailybar.FieldPriceChangeRateFromPreviousClose:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPriceChangeRateFromPreviousClose(v)
		return nil
	case dailybar.FieldTradedVolume:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTradedVolume(v)
		return nil
	case dailybar.FieldTradedAmount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTradedAmount(v)
		return nil
	case dailybar.FieldMarketCapitalization:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMarketCapitalization(v)
		return nil
	case dailybar.FieldExtensionsJSON:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExtensionsJSON(v)
		return nil
	case dailybar.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dailybar.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown DailyBar field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DailyBarMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DailyBarMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DailyBarMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DailyBar numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DailyBarMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DailyBarMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DailyBarMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DailyBar nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DailyBarMutation) ResetField(name string) error {
	switch name {
	case dailybar.FieldProvider:
		m.ResetProvider()
		return nil
	case dailybar.FieldProviderGroup:
		m.ResetProviderGroup()
		return nil
	case dailybar.FieldOperation:
		m.ResetOperation()
		return nil
	case dailybar.FieldMarket:
		m.ResetMarket()
		return nil
	case dailybar.FieldSecurityType:
		m.ResetSecurityType()
		return nil
	case dailybar.FieldSymbol:
		m.ResetSymbol()
		return nil
	case dailybar.FieldIsin:
		m.ResetIsin()
		return nil
	case dailybar.FieldName:
		m.ResetName()
		return nil
	case dailybar.FieldTradingDate:
		m.ResetTradingDate()
		return nil
	case dailybar.FieldCurrency:
		m.ResetCurrency()
		return nil
	case dailybar.FieldOpeningPrice:
		m.ResetOpeningPrice()
		return nil
	case dailybar.FieldHighestPrice:
		m.ResetHighestPrice()
		return nil
	case dailybar.FieldLowestPrice:
		m.ResetLowestPrice()
		return nil
	case dailybar.FieldClosingPrice:
		m.ResetClosingPrice()
		return nil
	case dailybar.FieldPriceChangeFromPreviousClose:
		m.ResetPriceChangeFromPreviousClose()
		return nil
	case dailybar.FieldPriceChangeRateFromPreviousClose:
		m.ResetPriceChangeRateFromPreviousClose()
		return nil
	case dailybar.FieldTradedVolume:
		m.ResetTradedVolume()
		return nil
	case dailybar.FieldTradedAmount:
		m.ResetTradedAmount()
		return nil
	case dailybar.FieldMarketCapitalization:
		m.ResetMarketCapitalization()
		return nil
	case dailybar.FieldExtensionsJSON:
		m.ResetExtensionsJSON()
		return nil
	case dailybar.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dailybar.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown DailyBar field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DailyBarMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DailyBarMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DailyBarMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DailyBarMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DailyBarMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DailyBarMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DailyBarMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DailyBar unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DailyBarMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DailyBar edge %s", name)
}
