// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DailyBarColumns holds the columns for the "daily_bar" table.
	DailyBarColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "provider_group", Type: field.TypeString},
		{Name: "operation", Type: field.TypeString},
		{Name: "market", Type: field.TypeString},
		{Name: "security_type", Type: field.TypeString},
		{Name: "symbol", Type: field.TypeString},
		{Name: "isin", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "trading_date", Type: field.TypeString},
		{Name: "currency", Type: field.TypeString, Default: ""},
		{Name: "opening_price", Type: field.TypeString, Default: ""},
		{Name: "highest_price", Type: field.TypeString, Default: ""},
		{Name: "lowest_price", Type: field.TypeString, Default: ""},
		{Name: "closing_price", Type: field.TypeString, Default: ""},
		{Name: "price_change_from_previous_close", Type: field.TypeString, Default: ""},
		{Name: "price_change_rate_from_previous_close", Type: field.TypeString, Default: ""},
		{Name: "traded_volume", Type: field.TypeString, Default: ""},
		{Name: "traded_amount", Type: field.TypeString, Default: ""},
		{Name: "market_capitalization", Type: field.TypeString, Default: ""},
		{Name: "extensions_json", Type: field.TypeString, Default: "{}"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DailyBarTable holds the schema information for the "daily_bar" table.
	DailyBarTable = &schema.Table{
		Name:       "daily_bar",
		Columns:    DailyBarColumns,
		PrimaryKey: []*schema.Column{DailyBarColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "daily_bar_natural_key",
				Unique:  true,
				Columns: []*schema.Column{DailyBarColumns[4], DailyBarColumns[5], DailyBarColumns[9], DailyBarColumns[6], DailyBarColumns[1], DailyBarColumns[2]},
			},
			{
				Name:    "idx_daily_bar_date",
				Unique:  false,
				Columns: []*schema.Column{DailyBarColumns[4], DailyBarColumns[5], DailyBarColumns[9]},
			},
			{
				Name:    "idx_daily_bar_symbol_date",
				Unique:  false,
				Columns: []*schema.Column{DailyBarColumns[4], DailyBarColumns[5], DailyBarColumns[6], DailyBarColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DailyBarTable,
	}
)

func init() {
	DailyBarTable.Annotation = &entsql.Annotation{
		Table: "daily_bar",
	}
}
