// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/ent/screenrunitem"
)

// ScreenRunItem is the model entity for the ScreenRunItem schema.
type ScreenRunItem struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ScreenRunID holds the value of the "screen_run_id" field.
	ScreenRunID string `json:"screen_run_id,omitempty"`
	// Ordinal holds the value of the "ordinal" field.
	Ordinal int `json:"ordinal,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// PayloadJSON holds the value of the "payload_json" field.
	PayloadJSON  []byte `json:"payload_json,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScreenRunItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case screenrunitem.FieldPayloadJSON:
			values[i] = new([]byte)
		case screenrunitem.FieldOrdinal:
			values[i] = new(sql.NullInt64)
		case screenrunitem.FieldID, screenrunitem.FieldScreenRunID, screenrunitem.FieldSymbol:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScreenRunItem fields.
func (_m *ScreenRunItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case screenrunitem.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case screenrunitem.FieldScreenRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field screen_run_id", values[i])
			} else if value.Valid {
				_m.ScreenRunID = value.String
			}
		case screenrunitem.FieldOrdinal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ordinal", values[i])
			} else if value.Valid {
				_m.Ordinal = int(value.Int64)
			}
		case screenrunitem.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case screenrunitem.FieldPayloadJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_json", values[i])
			} else if value != nil {
				_m.PayloadJSON = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScreenRunItem.
// This includes values selected through modifiers, order, etc.
func (_m *ScreenRunItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScreenRunItem.
// Note that you need to call ScreenRunItem.Unwrap() before calling this method if this ScreenRunItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScreenRunItem) Update() *ScreenRunItemUpdateOne {
	return NewScreenRunItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScreenRunItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScreenRunItem) Unwrap() *ScreenRunItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScreenRunItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScreenRunItem) String() string {
	var builder strings.Builder
	builder.WriteString("ScreenRunItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("screen_run_id=")
	builder.WriteString(_m.ScreenRunID)
	builder.WriteString(", ")
	builder.WriteString("ordinal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ordinal))
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	builder.WriteString("payload_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadJSON))
	builder.WriteByte(')')
	return builder.String()
}

// ScreenRunItems is a parsable slice of ScreenRunItem.
type ScreenRunItems []*ScreenRunItem
