// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/ent/screenrunitem"
)

// ScreenRunItemCreate is the builder for creating a ScreenRunItem entity.
type ScreenRunItemCreate struct {
	config
	mutation *ScreenRunItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScreenRunID sets the "screen_run_id" field.
func (_c *ScreenRunItemCreate) SetScreenRunID(v string) *ScreenRunItemCreate {
	_c.mutation.SetScreenRunID(v)
	return _c
}

// SetOrdinal sets the "ordinal" field.
func (_c *ScreenRunItemCreate) SetOrdinal(v int) *ScreenRunItemCreate {
	_c.mutation.SetOrdinal(v)
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *ScreenRunItemCreate) SetSymbol(v string) *ScreenRunItemCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_c *ScreenRunItemCreate) SetNillableSymbol(v *string) *ScreenRunItemCreate {
	if v != nil {
		_c.SetSymbol(*v)
	}
	return _c
}

// SetPayloadJSON sets the "payload_json" field.
func (_c *ScreenRunItemCreate) SetPayloadJSON(v []byte) *ScreenRunItemCreate {
	_c.mutation.SetPayloadJSON(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ScreenRunItemCreate) SetID(v string) *ScreenRunItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScreenRunItemMutation object of the builder.
func (_c *ScreenRunItemCreate) Mutation() *ScreenRunItemMutation {
	return _c.mutation
}

// Save creates the ScreenRunItem in the database.
func (_c *ScreenRunItemCreate) Save(ctx context.Context) (*ScreenRunItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScreenRunItemCreate) SaveX(ctx context.Context) *ScreenRunItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScreenRunItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScreenRunItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScreenRunItemCreate) defaults() {
	if _, ok := _c.mutation.Symbol(); !ok {
		v := screenrunitem.DefaultSymbol
		_c.mutation.SetSymbol(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScreenRunItemCreate) check() error {
	if _, ok := _c.mutation.ScreenRunID(); !ok {
		return &ValidationError{Name: "screen_run_id", err: errors.New(`ent: missing required field "ScreenRunItem.screen_run_id"`)}
	}
	if v, ok := _c.mutation.ScreenRunID(); ok {
		if err := screenrunitem.ScreenRunIDValidator(v); err != nil {
			return &ValidationError{Name: "screen_run_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRunItem.screen_run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ordinal(); !ok {
		return &ValidationError{Name: "ordinal", err: errors.New(`ent: missing required field "ScreenRunItem.ordinal"`)}
	}
	if v, ok := _c.mutation.Ordinal(); ok {
		if err := screenrunitem.OrdinalValidator(v); err != nil {
			return &ValidationError{Name: "ordinal", err: fmt.Errorf(`ent: validator failed for field "ScreenRunItem.ordinal": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "ScreenRunItem.symbol"`)}
	}
	if _, ok := _c.mutation.PayloadJSON(); !ok {
		return &ValidationError{Name: "payload_json", err: errors.New(`ent: missing required field "ScreenRunItem.payload_json"`)}
	}
	if v, ok := _c.mutation.PayloadJSON(); ok {
		if err := screenrunitem.PayloadJSONValidator(v); err != nil {
			return &ValidationError{Name: "payload_json", err: fmt.Errorf(`ent: validator failed for field "ScreenRunItem.payload_json": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := screenrunitem.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ScreenRunItem.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScreenRunItemCreate) sqlSave(ctx context.Context) (*ScreenRunItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScreenRunItem.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScreenRunItemCreate) createSpec() (*ScreenRunItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ScreenRunItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(screenrunitem.Table, sqlgraph.NewFieldSpec(screenrunitem.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ScreenRunID(); ok {
		_spec.SetField(screenrunitem.FieldScreenRunID, field.TypeString, value)
		_node.ScreenRunID = value
	}
	if value, ok := _c.mutation.Ordinal(); ok {
		_spec.SetField(screenrunitem.FieldOrdinal, field.TypeInt, value)
		_node.Ordinal = value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(screenrunitem.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := _c.mutation.PayloadJSON(); ok {
		_spec.SetField(screenrunitem.FieldPayloadJSON, field.TypeBytes, value)
		_node.PayloadJSON = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScreenRunItem.Create().
//		SetScreenRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScreenRunItemUpsert) {
//			SetScreenRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *ScreenRunItemCreate) OnConflict(opts ...sql.ConflictOption) *ScreenRunItemUpsertOne {
	_c.conflict = opts
	return &ScreenRunItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScreenRunItemCreate) OnConflictColumns(columns ...string) *ScreenRunItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScreenRunItemUpsertOne{
		create: _c,
	}
}

type (
	// ScreenRunItemUpsertOne is the builder for "upsert"-ing
	//  one ScreenRunItem node.
	ScreenRunItemUpsertOne struct {
		create *ScreenRunItemCreate
	}

	// ScreenRunItemUpsert is the "OnConflict" setter.
	ScreenRunItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetScreenRunID sets the "screen_run_id" field.
func (u *ScreenRunItemUpsert) SetScreenRunID(v string) *ScreenRunItemUpsert {
	u.Set(screenrunitem.FieldScreenRunID, v)
	return u
}

// UpdateScreenRunID sets the "screen_run_id" field to the value that was provided on create.
func (u *ScreenRunItemUpsert) UpdateScreenRunID() *ScreenRunItemUpsert {
	u.SetExcluded(screenrunitem.FieldScreenRunID)
	return u
}

// SetOrdinal sets the "ordinal" field.
func (u *ScreenRunItemUpsert) SetOrdinal(v int) *ScreenRunItemUpsert {
	u.Set(screenrunitem.FieldOrdinal, v)
	return u
}

// UpdateOrdinal sets the "ordinal" field to the value that was provided on create.
func (u *ScreenRunItemUpsert) UpdateOrdinal() *ScreenRunItemUpsert {
	u.SetExcluded(screenrunitem.FieldOrdinal)
	return u
}

// AddOrdinal adds v to the "ordinal" field.
func (u *ScreenRunItemUpsert) AddOrdinal(v int) *ScreenRunItemUpsert {
	u.Add(screenrunitem.FieldOrdinal, v)
	return u
}

// SetSymbol sets the "symbol" field.
func (u *ScreenRunItemUpsert) SetSymbol(v string) *ScreenRunItemUpsert {
	u.Set(screenrunitem.FieldSymbol, v)
	return u
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *ScreenRunItemUpsert) UpdateSymbol() *ScreenRunItemUpsert {
	u.SetExcluded(screenrunitem.FieldSymbol)
	return u
}

// SetPayloadJSON sets the "payload_json" field.
func (u *ScreenRunItemUpsert) SetPayloadJSON(v []byte) *ScreenRunItemUpsert {
	u.Set(screenrunitem.FieldPayloadJSON, v)
	return u
}

// UpdatePayloadJSON sets the "payload_json" field to the value that was provided on create.
func (u *ScreenRunItemUpsert) UpdatePayloadJSON() *ScreenRunItemUpsert {
	u.SetExcluded(screenrunitem.FieldPayloadJSON)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(screenrunitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScreenRunItemUpsertOne) UpdateNewValues() *ScreenRunItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(screenrunitem.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScreenRunItemUpsertOne) Ignore() *ScreenRunItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScreenRunItemUpsertOne) DoNothing() *ScreenRunItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScreenRunItemCreate.OnConflict
// documentation for more info.
func (u *ScreenRunItemUpsertOne) Update(set func(*ScreenRunItemUpsert)) *ScreenRunItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScreenRunItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetScreenRunID sets the "screen_run_id" field.
func (u *ScreenRunItemUpsertOne) SetScreenRunID(v string) *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetScreenRunID(v)
	})
}

// UpdateScreenRunID sets the "screen_run_id" field to the value that was provided on create.
func (u *ScreenRunItemUpsertOne) UpdateScreenRunID() *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateScreenRunID()
	})
}

// SetOrdinal sets the "ordinal" field.
func (u *ScreenRunItemUpsertOne) SetOrdinal(v int) *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetOrdinal(v)
	})
}

// AddOrdinal adds v to the "ordinal" field.
func (u *ScreenRunItemUpsertOne) AddOrdinal(v int) *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.AddOrdinal(v)
	})
}

// UpdateOrdinal sets the "ordinal" field to the value that was provided on create.
func (u *ScreenRunItemUpsertOne) UpdateOrdinal() *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateOrdinal()
	})
}

// SetSymbol sets the "symbol" field.
func (u *ScreenRunItemUpsertOne) SetSymbol(v string) *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *ScreenRunItemUpsertOne) UpdateSymbol() *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateSymbol()
	})
}

// SetPayloadJSON sets the "payload_json" field.
func (u *ScreenRunItemUpsertOne) SetPayloadJSON(v []byte) *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetPayloadJSON(v)
	})
}

// UpdatePayloadJSON sets the "payload_json" field to the value that was provided on create.
func (u *ScreenRunItemUpsertOne) UpdatePayloadJSON() *ScreenRunItemUpsertOne {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdatePayloadJSON()
	})
}

// Exec executes the query.
func (u *ScreenRunItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScreenRunItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScreenRunItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScreenRunItemUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ScreenRunItemUpsertOne.ID is not supported by MySQL driver. Use ScreenRunItemUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScreenRunItemUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScreenRunItemCreateBulk is the builder for creating many ScreenRunItem entities in bulk.
type ScreenRunItemCreateBulk struct {
	config
	err      error
	builders []*ScreenRunItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ScreenRunItem entities in the database.
func (_c *ScreenRunItemCreateBulk) Save(ctx context.Context) ([]*ScreenRunItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScreenRunItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScreenRunItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScreenRunItemCreateBulk) SaveX(ctx context.Context) []*ScreenRunItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScreenRunItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScreenRunItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScreenRunItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScreenRunItemUpsert) {
//			SetScreenRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *ScreenRunItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScreenRunItemUpsertBulk {
	_c.conflict = opts
	return &ScreenRunItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScreenRunItemCreateBulk) OnConflictColumns(columns ...string) *ScreenRunItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScreenRunItemUpsertBulk{
		create: _c,
	}
}

// ScreenRunItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ScreenRunItem nodes.
type ScreenRunItemUpsertBulk struct {
	create *ScreenRunItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(screenrunitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScreenRunItemUpsertBulk) UpdateNewValues() *ScreenRunItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(screenrunitem.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScreenRunItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScreenRunItemUpsertBulk) Ignore() *ScreenRunItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScreenRunItemUpsertBulk) DoNothing() *ScreenRunItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScreenRunItemCreateBulk.OnConflict
// documentation for more info.
func (u *ScreenRunItemUpsertBulk) Update(set func(*ScreenRunItemUpsert)) *ScreenRunItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScreenRunItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetScreenRunID sets the "screen_run_id" field.
func (u *ScreenRunItemUpsertBulk) SetScreenRunID(v string) *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetScreenRunID(v)
	})
}

// UpdateScreenRunID sets the "screen_run_id" field to the value that was provided on create.
func (u *ScreenRunItemUpsertBulk) UpdateScreenRunID() *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateScreenRunID()
	})
}

// SetOrdinal sets the "ordinal" field.
func (u *ScreenRunItemUpsertBulk) SetOrdinal(v int) *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetOrdinal(v)
	})
}

// AddOrdinal adds v to the "ordinal" field.
func (u *ScreenRunItemUpsertBulk) AddOrdinal(v int) *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.AddOrdinal(v)
	})
}

// UpdateOrdinal sets the "ordinal" field to the value that was provided on create.
func (u *ScreenRunItemUpsertBulk) UpdateOrdinal() *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateOrdinal()
	})
}

// SetSymbol sets the "symbol" field.
func (u *ScreenRunItemUpsertBulk) SetSymbol(v string) *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *ScreenRunItemUpsertBulk) UpdateSymbol() *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdateSymbol()
	})
}

// SetPayloadJSON sets the "payload_json" field.
func (u *ScreenRunItemUpsertBulk) SetPayloadJSON(v []byte) *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.SetPayloadJSON(v)
	})
}

// UpdatePayloadJSON sets the "payload_json" field to the value that was provided on create.
func (u *ScreenRunItemUpsertBulk) UpdatePayloadJSON() *ScreenRunItemUpsertBulk {
	return u.Update(func(s *ScreenRunItemUpsert) {
		s.UpdatePayloadJSON()
	})
}

// Exec executes the query.
func (u *ScreenRunItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScreenRunItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScreenRunItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScreenRunItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
