// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/ent/screenrun"
)

// ScreenRunCreate is the builder for creating a ScreenRun entity.
type ScreenRunCreate struct {
	config
	mutation *ScreenRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAlias sets the "alias" field.
func (_c *ScreenRunCreate) SetAlias(v string) *ScreenRunCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableAlias(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetStrategyID sets the "strategy_id" field.
func (_c *ScreenRunCreate) SetStrategyID(v string) *ScreenRunCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (_c *ScreenRunCreate) SetStrategyVersionID(v string) *ScreenRunCreate {
	_c.mutation.SetStrategyVersionID(v)
	return _c
}

// SetQueryHash sets the "query_hash" field.
func (_c *ScreenRunCreate) SetQueryHash(v string) *ScreenRunCreate {
	_c.mutation.SetQueryHash(v)
	return _c
}

// SetInputDataset sets the "input_dataset" field.
func (_c *ScreenRunCreate) SetInputDataset(v string) *ScreenRunCreate {
	_c.mutation.SetInputDataset(v)
	return _c
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (_c *ScreenRunCreate) SetInputSchemaVersion(v int) *ScreenRunCreate {
	_c.mutation.SetInputSchemaVersion(v)
	return _c
}

// SetParamsJSON sets the "params_json" field.
func (_c *ScreenRunCreate) SetParamsJSON(v []byte) *ScreenRunCreate {
	_c.mutation.SetParamsJSON(v)
	return _c
}

// SetDataFrom sets the "data_from" field.
func (_c *ScreenRunCreate) SetDataFrom(v string) *ScreenRunCreate {
	_c.mutation.SetDataFrom(v)
	return _c
}

// SetNillableDataFrom sets the "data_from" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableDataFrom(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetDataFrom(*v)
	}
	return _c
}

// SetDataTo sets the "data_to" field.
func (_c *ScreenRunCreate) SetDataTo(v string) *ScreenRunCreate {
	_c.mutation.SetDataTo(v)
	return _c
}

// SetNillableDataTo sets the "data_to" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableDataTo(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetDataTo(*v)
	}
	return _c
}

// SetDataAsOf sets the "data_as_of" field.
func (_c *ScreenRunCreate) SetDataAsOf(v string) *ScreenRunCreate {
	_c.mutation.SetDataAsOf(v)
	return _c
}

// SetNillableDataAsOf sets the "data_as_of" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableDataAsOf(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetDataAsOf(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ScreenRunCreate) SetStartedAt(v time.Time) *ScreenRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableStartedAt(v *time.Time) *ScreenRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ScreenRunCreate) SetFinishedAt(v time.Time) *ScreenRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableFinishedAt(v *time.Time) *ScreenRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScreenRunCreate) SetStatus(v string) *ScreenRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetResultCount sets the "result_count" field.
func (_c *ScreenRunCreate) SetResultCount(v int) *ScreenRunCreate {
	_c.mutation.SetResultCount(v)
	return _c
}

// SetResultHash sets the "result_hash" field.
func (_c *ScreenRunCreate) SetResultHash(v string) *ScreenRunCreate {
	_c.mutation.SetResultHash(v)
	return _c
}

// SetNillableResultHash sets the "result_hash" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableResultHash(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetResultHash(*v)
	}
	return _c
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (_c *ScreenRunCreate) SetResultSizeBytes(v int64) *ScreenRunCreate {
	_c.mutation.SetResultSizeBytes(v)
	return _c
}

// SetSummaryJSON sets the "summary_json" field.
func (_c *ScreenRunCreate) SetSummaryJSON(v []byte) *ScreenRunCreate {
	_c.mutation.SetSummaryJSON(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ScreenRunCreate) SetErrorMessage(v string) *ScreenRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ScreenRunCreate) SetNillableErrorMessage(v *string) *ScreenRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScreenRunCreate) SetID(v string) *ScreenRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScreenRunMutation object of the builder.
func (_c *ScreenRunCreate) Mutation() *ScreenRunMutation {
	return _c.mutation
}

// Save creates the ScreenRun in the database.
func (_c *ScreenRunCreate) Save(ctx context.Context) (*ScreenRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScreenRunCreate) SaveX(ctx context.Context) *ScreenRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScreenRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScreenRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScreenRunCreate) defaults() {
	if _, ok := _c.mutation.DataFrom(); !ok {
		v := screenrun.DefaultDataFrom
		_c.mutation.SetDataFrom(v)
	}
	if _, ok := _c.mutation.DataTo(); !ok {
		v := screenrun.DefaultDataTo
		_c.mutation.SetDataTo(v)
	}
	if _, ok := _c.mutation.DataAsOf(); !ok {
		v := screenrun.DefaultDataAsOf
		_c.mutation.SetDataAsOf(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := screenrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.ResultHash(); !ok {
		v := screenrun.DefaultResultHash
		_c.mutation.SetResultHash(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := screenrun.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScreenRunCreate) check() error {
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "ScreenRun.strategy_id"`)}
	}
	if v, ok := _c.mutation.StrategyID(); ok {
		if err := screenrun.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StrategyVersionID(); !ok {
		return &ValidationError{Name: "strategy_version_id", err: errors.New(`ent: missing required field "ScreenRun.strategy_version_id"`)}
	}
	if v, ok := _c.mutation.StrategyVersionID(); ok {
		if err := screenrun.StrategyVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_version_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QueryHash(); !ok {
		return &ValidationError{Name: "query_hash", err: errors.New(`ent: missing required field "ScreenRun.query_hash"`)}
	}
	if v, ok := _c.mutation.QueryHash(); ok {
		if err := screenrun.QueryHashValidator(v); err != nil {
			return &ValidationError{Name: "query_hash", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.query_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputDataset(); !ok {
		return &ValidationError{Name: "input_dataset", err: errors.New(`ent: missing required field "ScreenRun.input_dataset"`)}
	}
	if v, ok := _c.mutation.InputDataset(); ok {
		if err := screenrun.InputDatasetValidator(v); err != nil {
			return &ValidationError{Name: "input_dataset", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_dataset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputSchemaVersion(); !ok {
		return &ValidationError{Name: "input_schema_version", err: errors.New(`ent: missing required field "ScreenRun.input_schema_version"`)}
	}
	if v, ok := _c.mutation.InputSchemaVersion(); ok {
		if err := screenrun.InputSchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "input_schema_version", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_schema_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataFrom(); !ok {
		return &ValidationError{Name: "data_from", err: errors.New(`ent: missing required field "ScreenRun.data_from"`)}
	}
	if _, ok := _c.mutation.DataTo(); !ok {
		return &ValidationError{Name: "data_to", err: errors.New(`ent: missing required field "ScreenRun.data_to"`)}
	}
	if _, ok := _c.mutation.DataAsOf(); !ok {
		return &ValidationError{Name: "data_as_of", err: errors.New(`ent: missing required field "ScreenRun.data_as_of"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ScreenRun.started_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ScreenRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := screenrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResultCount(); !ok {
		return &ValidationError{Name: "result_count", err: errors.New(`ent: missing required field "ScreenRun.result_count"`)}
	}
	if v, ok := _c.mutation.ResultCount(); ok {
		if err := screenrun.ResultCountValidator(v); err != nil {
			return &ValidationError{Name: "result_count", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResultHash(); !ok {
		return &ValidationError{Name: "result_hash", err: errors.New(`ent: missing required field "ScreenRun.result_hash"`)}
	}
	if _, ok := _c.mutation.ResultSizeBytes(); !ok {
		return &ValidationError{Name: "result_size_bytes", err: errors.New(`ent: missing required field "ScreenRun.result_size_bytes"`)}
	}
	if v, ok := _c.mutation.ResultSizeBytes(); ok {
		if err := screenrun.ResultSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "result_size_bytes", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "ScreenRun.error_message"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := screenrun.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScreenRunCreate) sqlSave(ctx context.Context) (*ScreenRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScreenRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScreenRunCreate) createSpec() (*ScreenRun, *sqlgraph.CreateSpec) {
	var (
		_node = &ScreenRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(screenrun.Table, sqlgraph.NewFieldSpec(screenrun.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(screenrun.FieldAlias, field.TypeString, value)
		_node.Alias = &value
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(screenrun.FieldStrategyID, field.TypeString, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.StrategyVersionID(); ok {
		_spec.SetField(screenrun.FieldStrategyVersionID, field.TypeString, value)
		_node.StrategyVersionID = value
	}
	if value, ok := _c.mutation.QueryHash(); ok {
		_spec.SetField(screenrun.FieldQueryHash, field.TypeString, value)
		_node.QueryHash = value
	}
	if value, ok := _c.mutation.InputDataset(); ok {
		_spec.SetField(screenrun.FieldInputDataset, field.TypeString, value)
		_node.InputDataset = value
	}
	if value, ok := _c.mutation.InputSchemaVersion(); ok {
		_spec.SetField(screenrun.FieldInputSchemaVersion, field.TypeInt, value)
		_node.InputSchemaVersion = value
	}
	if value, ok := _c.mutation.ParamsJSON(); ok {
		_spec.SetField(screenrun.FieldParamsJSON, field.TypeBytes, value)
		_node.ParamsJSON = value
	}
	if value, ok := _c.mutation.DataFrom(); ok {
		_spec.SetField(screenrun.FieldDataFrom, field.TypeString, value)
		_node.DataFrom = value
	}
	if value, ok := _c.mutation.DataTo(); ok {
		_spec.SetField(screenrun.FieldDataTo, field.TypeString, value)
		_node.DataTo = value
	}
	if value, ok := _c.mutation.DataAsOf(); ok {
		_spec.SetField(screenrun.FieldDataAsOf, field.TypeString, value)
		_node.DataAsOf = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(screenrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(screenrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(screenrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ResultCount(); ok {
		_spec.SetField(screenrun.FieldResultCount, field.TypeInt, value)
		_node.ResultCount = value
	}
	if value, ok := _c.mutation.ResultHash(); ok {
		_spec.SetField(screenrun.FieldResultHash, field.TypeString, value)
		_node.ResultHash = value
	}
	if value, ok := _c.mutation.ResultSizeBytes(); ok {
		_spec.SetField(screenrun.FieldResultSizeBytes, field.TypeInt64, value)
		_node.ResultSizeBytes = value
	}
	if value, ok := _c.mutation.SummaryJSON(); ok {
		_spec.SetField(screenrun.FieldSummaryJSON, field.TypeBytes, value)
		_node.SummaryJSON = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(screenrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScreenRun.Create().
//		SetAlias(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScreenRunUpsert) {
//			SetAlias(v+v).
//		}).
//		Exec(ctx)
func (_c *ScreenRunCreate) OnConflict(opts ...sql.ConflictOption) *ScreenRunUpsertOne {
	_c.conflict = opts
	return &ScreenRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScreenRunCreate) OnConflictColumns(columns ...string) *ScreenRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScreenRunUpsertOne{
		create: _c,
	}
}

type (
	// ScreenRunUpsertOne is the builder for "upsert"-ing
	//  one ScreenRun node.
	ScreenRunUpsertOne struct {
		create *ScreenRunCreate
	}

	// ScreenRunUpsert is the "OnConflict" setter.
	ScreenRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetAlias sets the "alias" field.
func (u *ScreenRunUpsert) SetAlias(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldAlias, v)
	return u
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateAlias() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldAlias)
	return u
}

// ClearAlias clears the value of the "alias" field.
func (u *ScreenRunUpsert) ClearAlias() *ScreenRunUpsert {
	u.SetNull(screenrun.FieldAlias)
	return u
}

// SetStrategyID sets the "strategy_id" field.
func (u *ScreenRunUpsert) SetStrategyID(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldStrategyID, v)
	return u
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateStrategyID() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldStrategyID)
	return u
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (u *ScreenRunUpsert) SetStrategyVersionID(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldStrategyVersionID, v)
	return u
}

// UpdateStrategyVersionID sets the "strategy_version_id" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateStrategyVersionID() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldStrategyVersionID)
	return u
}

// SetQueryHash sets the "query_hash" field.
func (u *ScreenRunUpsert) SetQueryHash(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldQueryHash, v)
	return u
}

// UpdateQueryHash sets the "query_hash" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateQueryHash() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldQueryHash)
	return u
}

// SetInputDataset sets the "input_dataset" field.
func (u *ScreenRunUpsert) SetInputDataset(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldInputDataset, v)
	return u
}

// UpdateInputDataset sets the "input_dataset" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateInputDataset() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldInputDataset)
	return u
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (u *ScreenRunUpsert) SetInputSchemaVersion(v int) *ScreenRunUpsert {
	u.Set(screenrun.FieldInputSchemaVersion, v)
	return u
}

// UpdateInputSchemaVersion sets the "input_schema_version" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateInputSchemaVersion() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldInputSchemaVersion)
	return u
}

// AddInputSchemaVersion adds v to the "input_schema_version" field.
func (u *ScreenRunUpsert) AddInputSchemaVersion(v int) *ScreenRunUpsert {
	u.Add(screenrun.FieldInputSchemaVersion, v)
	return u
}

// SetParamsJSON sets the "params_json" field.
func (u *ScreenRunUpsert) SetParamsJSON(v []byte) *ScreenRunUpsert {
	u.Set(screenrun.FieldParamsJSON, v)
	return u
}

// UpdateParamsJSON sets the "params_json" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateParamsJSON() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldParamsJSON)
	return u
}

// ClearParamsJSON clears the value of the "params_json" field.
func (u *ScreenRunUpsert) ClearParamsJSON() *ScreenRunUpsert {
	u.SetNull(screenrun.FieldParamsJSON)
	return u
}

// SetDataFrom sets the "data_from" field.
func (u *ScreenRunUpsert) SetDataFrom(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldDataFrom, v)
	return u
}

// UpdateDataFrom sets the "data_from" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateDataFrom() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldDataFrom)
	return u
}

// SetDataTo sets the "data_to" field.
func (u *ScreenRunUpsert) SetDataTo(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldDataTo, v)
	return u
}

// UpdateDataTo sets the "data_to" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateDataTo() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldDataTo)
	return u
}

// SetDataAsOf sets the "data_as_of" field.
func (u *ScreenRunUpsert) SetDataAsOf(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldDataAsOf, v)
	return u
}

// UpdateDataAsOf sets the "data_as_of" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateDataAsOf() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldDataAsOf)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *ScreenRunUpsert) SetFinishedAt(v time.Time) *ScreenRunUpsert {
	u.Set(screenrun.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateFinishedAt() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ScreenRunUpsert) ClearFinishedAt() *ScreenRunUpsert {
	u.SetNull(screenrun.FieldFinishedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *ScreenRunUpsert) SetStatus(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateStatus() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldStatus)
	return u
}

// SetResultCount sets the "result_count" field.
func (u *ScreenRunUpsert) SetResultCount(v int) *ScreenRunUpsert {
	u.Set(screenrun.FieldResultCount, v)
	return u
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateResultCount() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldResultCount)
	return u
}

// AddResultCount adds v to the "result_count" field.
func (u *ScreenRunUpsert) AddResultCount(v int) *ScreenRunUpsert {
	u.Add(screenrun.FieldResultCount, v)
	return u
}

// SetResultHash sets the "result_hash" field.
func (u *ScreenRunUpsert) SetResultHash(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldResultHash, v)
	return u
}

// UpdateResultHash sets the "result_hash" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateResultHash() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldResultHash)
	return u
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (u *ScreenRunUpsert) SetResultSizeBytes(v int64) *ScreenRunUpsert {
	u.Set(screenrun.FieldResultSizeBytes, v)
	return u
}

// UpdateResultSizeBytes sets the "result_size_bytes" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateResultSizeBytes() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldResultSizeBytes)
	return u
}

// AddResultSizeBytes adds v to the "result_size_bytes" field.
func (u *ScreenRunUpsert) AddResultSizeBytes(v int64) *ScreenRunUpsert {
	u.Add(screenrun.FieldResultSizeBytes, v)
	return u
}

// SetSummaryJSON sets the "summary_json" field.
func (u *ScreenRunUpsert) SetSummaryJSON(v []byte) *ScreenRunUpsert {
	u.Set(screenrun.FieldSummaryJSON, v)
	return u
}

// UpdateSummaryJSON sets the "summary_json" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateSummaryJSON() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldSummaryJSON)
	return u
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (u *ScreenRunUpsert) ClearSummaryJSON() *ScreenRunUpsert {
	u.SetNull(screenrun.FieldSummaryJSON)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ScreenRunUpsert) SetErrorMessage(v string) *ScreenRunUpsert {
	u.Set(screenrun.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ScreenRunUpsert) UpdateErrorMessage() *ScreenRunUpsert {
	u.SetExcluded(screenrun.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(screenrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScreenRunUpsertOne) UpdateNewValues() *ScreenRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(screenrun.FieldID)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(screenrun.FieldStartedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScreenRunUpsertOne) Ignore() *ScreenRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScreenRunUpsertOne) DoNothing() *ScreenRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScreenRunCreate.OnConflict
// documentation for more info.
func (u *ScreenRunUpsertOne) Update(set func(*ScreenRunUpsert)) *ScreenRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScreenRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlias sets the "alias" field.
func (u *ScreenRunUpsertOne) SetAlias(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateAlias() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateAlias()
	})
}

// ClearAlias clears the value of the "alias" field.
func (u *ScreenRunUpsertOne) ClearAlias() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearAlias()
	})
}

// SetStrategyID sets the "strategy_id" field.
func (u *ScreenRunUpsertOne) SetStrategyID(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStrategyID(v)
	})
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateStrategyID() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStrategyID()
	})
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (u *ScreenRunUpsertOne) SetStrategyVersionID(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStrategyVersionID(v)
	})
}

// UpdateStrategyVersionID sets the "strategy_version_id" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateStrategyVersionID() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStrategyVersionID()
	})
}

// SetQueryHash sets the "query_hash" field.
func (u *ScreenRunUpsertOne) SetQueryHash(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetQueryHash(v)
	})
}

// UpdateQueryHash sets the "query_hash" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateQueryHash() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateQueryHash()
	})
}

// SetInputDataset sets the "input_dataset" field.
func (u *ScreenRunUpsertOne) SetInputDataset(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetInputDataset(v)
	})
}

// UpdateInputDataset sets the "input_dataset" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateInputDataset() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateInputDataset()
	})
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (u *ScreenRunUpsertOne) SetInputSchemaVersion(v int) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetInputSchemaVersion(v)
	})
}

// AddInputSchemaVersion adds v to the "input_schema_version" field.
func (u *ScreenRunUpsertOne) AddInputSchemaVersion(v int) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddInputSchemaVersion(v)
	})
}

// UpdateInputSchemaVersion sets the "input_schema_version" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateInputSchemaVersion() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateInputSchemaVersion()
	})
}

// SetParamsJSON sets the "params_json" field.
func (u *ScreenRunUpsertOne) SetParamsJSON(v []byte) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetParamsJSON(v)
	})
}

// UpdateParamsJSON sets the "params_json" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateParamsJSON() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateParamsJSON()
	})
}

// ClearParamsJSON clears the value of the "params_json" field.
func (u *ScreenRunUpsertOne) ClearParamsJSON() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearParamsJSON()
	})
}

// SetDataFrom sets the "data_from" field.
func (u *ScreenRunUpsertOne) SetDataFrom(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataFrom(v)
	})
}

// UpdateDataFrom sets the "data_from" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateDataFrom() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataFrom()
	})
}

// SetDataTo sets the "data_to" field.
func (u *ScreenRunUpsertOne) SetDataTo(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataTo(v)
	})
}

// UpdateDataTo sets the "data_to" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateDataTo() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataTo()
	})
}

// SetDataAsOf sets the "data_as_of" field.
func (u *ScreenRunUpsertOne) SetDataAsOf(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataAsOf(v)
	})
}

// UpdateDataAsOf sets the "data_as_of" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateDataAsOf() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataAsOf()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *ScreenRunUpsertOne) SetFinishedAt(v time.Time) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateFinishedAt() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ScreenRunUpsertOne) ClearFinishedAt() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ScreenRunUpsertOne) SetStatus(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateStatus() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStatus()
	})
}

// SetResultCount sets the "result_count" field.
func (u *ScreenRunUpsertOne) SetResultCount(v int) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *ScreenRunUpsertOne) AddResultCount(v int) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateResultCount() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultCount()
	})
}

// SetResultHash sets the "result_hash" field.
func (u *ScreenRunUpsertOne) SetResultHash(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultHash(v)
	})
}

// UpdateResultHash sets the "result_hash" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateResultHash() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultHash()
	})
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (u *ScreenRunUpsertOne) SetResultSizeBytes(v int64) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultSizeBytes(v)
	})
}

// AddResultSizeBytes adds v to the "result_size_bytes" field.
func (u *ScreenRunUpsertOne) AddResultSizeBytes(v int64) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddResultSizeBytes(v)
	})
}

// UpdateResultSizeBytes sets the "result_size_bytes" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateResultSizeBytes() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultSizeBytes()
	})
}

// SetSummaryJSON sets the "summary_json" field.
func (u *ScreenRunUpsertOne) SetSummaryJSON(v []byte) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetSummaryJSON(v)
	})
}

// UpdateSummaryJSON sets the "summary_json" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateSummaryJSON() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateSummaryJSON()
	})
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (u *ScreenRunUpsertOne) ClearSummaryJSON() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearSummaryJSON()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ScreenRunUpsertOne) SetErrorMessage(v string) *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ScreenRunUpsertOne) UpdateErrorMessage() *ScreenRunUpsertOne {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// Exec executes the query.
func (u *ScreenRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScreenRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScreenRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScreenRunUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ScreenRunUpsertOne.ID is not supported by MySQL driver. Use ScreenRunUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScreenRunUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScreenRunCreateBulk is the builder for creating many ScreenRun entities in bulk.
type ScreenRunCreateBulk struct {
	config
	err      error
	builders []*ScreenRunCreate
	conflict []sql.ConflictOption
}

// Save creates the ScreenRun entities in the database.
func (_c *ScreenRunCreateBulk) Save(ctx context.Context) ([]*ScreenRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScreenRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScreenRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScreenRunCreateBulk) SaveX(ctx context.Context) []*ScreenRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScreenRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScreenRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScreenRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScreenRunUpsert) {
//			SetAlias(v+v).
//		}).
//		Exec(ctx)
func (_c *ScreenRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScreenRunUpsertBulk {
	_c.conflict = opts
	return &ScreenRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScreenRunCreateBulk) OnConflictColumns(columns ...string) *ScreenRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScreenRunUpsertBulk{
		create: _c,
	}
}

// ScreenRunUpsertBulk is the builder for "upsert"-ing
// a bulk of ScreenRun nodes.
type ScreenRunUpsertBulk struct {
	create *ScreenRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(screenrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScreenRunUpsertBulk) UpdateNewValues() *ScreenRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(screenrun.FieldID)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(screenrun.FieldStartedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScreenRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScreenRunUpsertBulk) Ignore() *ScreenRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScreenRunUpsertBulk) DoNothing() *ScreenRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScreenRunCreateBulk.OnConflict
// documentation for more info.
func (u *ScreenRunUpsertBulk) Update(set func(*ScreenRunUpsert)) *ScreenRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScreenRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetAlias sets the "alias" field.
func (u *ScreenRunUpsertBulk) SetAlias(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetAlias(v)
	})
}

// UpdateAlias sets the "alias" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateAlias() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateAlias()
	})
}

// ClearAlias clears the value of the "alias" field.
func (u *ScreenRunUpsertBulk) ClearAlias() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearAlias()
	})
}

// SetStrategyID sets the "strategy_id" field.
func (u *ScreenRunUpsertBulk) SetStrategyID(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStrategyID(v)
	})
}

// UpdateStrategyID sets the "strategy_id" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateStrategyID() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStrategyID()
	})
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (u *ScreenRunUpsertBulk) SetStrategyVersionID(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStrategyVersionID(v)
	})
}

// UpdateStrategyVersionID sets the "strategy_version_id" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateStrategyVersionID() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStrategyVersionID()
	})
}

// SetQueryHash sets the "query_hash" field.
func (u *ScreenRunUpsertBulk) SetQueryHash(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetQueryHash(v)
	})
}

// UpdateQueryHash sets the "query_hash" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateQueryHash() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateQueryHash()
	})
}

// SetInputDataset sets the "input_dataset" field.
func (u *ScreenRunUpsertBulk) SetInputDataset(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetInputDataset(v)
	})
}

// UpdateInputDataset sets the "input_dataset" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateInputDataset() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateInputDataset()
	})
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (u *ScreenRunUpsertBulk) SetInputSchemaVersion(v int) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetInputSchemaVersion(v)
	})
}

// AddInputSchemaVersion adds v to the "input_schema_version" field.
func (u *ScreenRunUpsertBulk) AddInputSchemaVersion(v int) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddInputSchemaVersion(v)
	})
}

// UpdateInputSchemaVersion sets the "input_schema_version" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateInputSchemaVersion() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateInputSchemaVersion()
	})
}

// SetParamsJSON sets the "params_json" field.
func (u *ScreenRunUpsertBulk) SetParamsJSON(v []byte) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetParamsJSON(v)
	})
}

// UpdateParamsJSON sets the "params_json" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateParamsJSON() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateParamsJSON()
	})
}

// ClearParamsJSON clears the value of the "params_json" field.
func (u *ScreenRunUpsertBulk) ClearParamsJSON() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearParamsJSON()
	})
}

// SetDataFrom sets the "data_from" field.
func (u *ScreenRunUpsertBulk) SetDataFrom(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataFrom(v)
	})
}

// UpdateDataFrom sets the "data_from" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateDataFrom() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataFrom()
	})
}

// SetDataTo sets the "data_to" field.
func (u *ScreenRunUpsertBulk) SetDataTo(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataTo(v)
	})
}

// UpdateDataTo sets the "data_to" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateDataTo() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataTo()
	})
}

// SetDataAsOf sets the "data_as_of" field.
func (u *ScreenRunUpsertBulk) SetDataAsOf(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetDataAsOf(v)
	})
}

// UpdateDataAsOf sets the "data_as_of" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateDataAsOf() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateDataAsOf()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *ScreenRunUpsertBulk) SetFinishedAt(v time.Time) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateFinishedAt() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *ScreenRunUpsertBulk) ClearFinishedAt() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetStatus sets the "status" field.
func (u *ScreenRunUpsertBulk) SetStatus(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateStatus() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateStatus()
	})
}

// SetResultCount sets the "result_count" field.
func (u *ScreenRunUpsertBulk) SetResultCount(v int) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultCount(v)
	})
}

// AddResultCount adds v to the "result_count" field.
func (u *ScreenRunUpsertBulk) AddResultCount(v int) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddResultCount(v)
	})
}

// UpdateResultCount sets the "result_count" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateResultCount() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultCount()
	})
}

// SetResultHash sets the "result_hash" field.
func (u *ScreenRunUpsertBulk) SetResultHash(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultHash(v)
	})
}

// UpdateResultHash sets the "result_hash" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateResultHash() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultHash()
	})
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (u *ScreenRunUpsertBulk) SetResultSizeBytes(v int64) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetResultSizeBytes(v)
	})
}

// AddResultSizeBytes adds v to the "result_size_bytes" field.
func (u *ScreenRunUpsertBulk) AddResultSizeBytes(v int64) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.AddResultSizeBytes(v)
	})
}

// UpdateResultSizeBytes sets the "result_size_bytes" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateResultSizeBytes() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateResultSizeBytes()
	})
}

// SetSummaryJSON sets the "summary_json" field.
func (u *ScreenRunUpsertBulk) SetSummaryJSON(v []byte) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetSummaryJSON(v)
	})
}

// UpdateSummaryJSON sets the "summary_json" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateSummaryJSON() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateSummaryJSON()
	})
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (u *ScreenRunUpsertBulk) ClearSummaryJSON() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.ClearSummaryJSON()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ScreenRunUpsertBulk) SetErrorMessage(v string) *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ScreenRunUpsertBulk) UpdateErrorMessage() *ScreenRunUpsertBulk {
	return u.Update(func(s *ScreenRunUpsert) {
		s.UpdateErrorMessage()
	})
}

// Exec executes the query.
func (u *ScreenRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScreenRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScreenRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScreenRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
