// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/ent/screenrun"
)

// ScreenRun is the model entity for the ScreenRun schema.
type ScreenRun struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias *string `json:"alias,omitempty"`
	// StrategyID holds the value of the "strategy_id" field.
	StrategyID string `json:"strategy_id,omitempty"`
	// StrategyVersionID holds the value of the "strategy_version_id" field.
	StrategyVersionID string `json:"strategy_version_id,omitempty"`
	// QueryHash holds the value of the "query_hash" field.
	QueryHash string `json:"query_hash,omitempty"`
	// InputDataset holds the value of the "input_dataset" field.
	InputDataset string `json:"input_dataset,omitempty"`
	// InputSchemaVersion holds the value of the "input_schema_version" field.
	InputSchemaVersion int `json:"input_schema_version,omitempty"`
	// ParamsJSON holds the value of the "params_json" field.
	ParamsJSON []byte `json:"params_json,omitempty"`
	// DataFrom holds the value of the "data_from" field.
	DataFrom string `json:"data_from,omitempty"`
	// DataTo holds the value of the "data_to" field.
	DataTo string `json:"data_to,omitempty"`
	// DataAsOf holds the value of the "data_as_of" field.
	DataAsOf string `json:"data_as_of,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ResultCount holds the value of the "result_count" field.
	ResultCount int `json:"result_count,omitempty"`
	// ResultHash holds the value of the "result_hash" field.
	ResultHash string `json:"result_hash,omitempty"`
	// ResultSizeBytes holds the value of the "result_size_bytes" field.
	ResultSizeBytes int64 `json:"result_size_bytes,omitempty"`
	// SummaryJSON holds the value of the "summary_json" field.
	SummaryJSON []byte `json:"summary_json,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScreenRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case screenrun.FieldParamsJSON, screenrun.FieldSummaryJSON:
			values[i] = new([]byte)
		case screenrun.FieldInputSchemaVersion, screenrun.FieldResultCount, screenrun.FieldResultSizeBytes:
			values[i] = new(sql.NullInt64)
		case screenrun.FieldID, screenrun.FieldAlias, screenrun.FieldStrategyID, screenrun.FieldStrategyVersionID, screenrun.FieldQueryHash, screenrun.FieldInputDataset, screenrun.FieldDataFrom, screenrun.FieldDataTo, screenrun.FieldDataAsOf, screenrun.FieldStatus, screenrun.FieldResultHash, screenrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case screenrun.FieldStartedAt, screenrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScreenRun fields.
func (_m *ScreenRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case screenrun.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case screenrun.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = new(string)
				*_m.Alias = value.String
			}
		case screenrun.FieldStrategyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value.Valid {
				_m.StrategyID = value.String
			}
		case screenrun.FieldStrategyVersionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_version_id", values[i])
			} else if value.Valid {
				_m.StrategyVersionID = value.String
			}
		case screenrun.FieldQueryHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query_hash", values[i])
			} else if value.Valid {
				_m.QueryHash = value.String
			}
		case screenrun.FieldInputDataset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_dataset", values[i])
			} else if value.Valid {
				_m.InputDataset = value.String
			}
		case screenrun.FieldInputSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_schema_version", values[i])
			} else if value.Valid {
				_m.InputSchemaVersion = int(value.Int64)
			}
		case screenrun.FieldParamsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field params_json", values[i])
			} else if value != nil {
				_m.ParamsJSON = *value
			}
		case screenrun.FieldDataFrom:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_from", values[i])
			} else if value.Valid {
				_m.DataFrom = value.String
			}
		case screenrun.FieldDataTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_to", values[i])
			} else if value.Valid {
				_m.DataTo = value.String
			}
		case screenrun.FieldDataAsOf:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_as_of", values[i])
			} else if value.Valid {
				_m.DataAsOf = value.String
			}
		case screenrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case screenrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case screenrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case screenrun.FieldResultCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_count", values[i])
			} else if value.Valid {
				_m.ResultCount = int(value.Int64)
			}
		case screenrun.FieldResultHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_hash", values[i])
			} else if value.Valid {
				_m.ResultHash = value.String
			}
		case screenrun.FieldResultSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_size_bytes", values[i])
			} else if value.Valid {
				_m.ResultSizeBytes = value.Int64
			}
		case screenrun.FieldSummaryJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field summary_json", values[i])
			} else if value != nil {
				_m.SummaryJSON = *value
			}
		case screenrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScreenRun.
// This includes values selected through modifiers, order, etc.
func (_m *ScreenRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScreenRun.
// Note that you need to call ScreenRun.Unwrap() before calling this method if this ScreenRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScreenRun) Update() *ScreenRunUpdateOne {
	return NewScreenRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScreenRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScreenRun) Unwrap() *ScreenRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScreenRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScreenRun) String() string {
	var builder strings.Builder
	builder.WriteString("ScreenRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.Alias; v != nil {
		builder.WriteString("alias=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("strategy_id=")
	builder.WriteString(_m.StrategyID)
	builder.WriteString(", ")
	builder.WriteString("strategy_version_id=")
	builder.WriteString(_m.StrategyVersionID)
	builder.WriteString(", ")
	builder.WriteString("query_hash=")
	builder.WriteString(_m.QueryHash)
	builder.WriteString(", ")
	builder.WriteString("input_dataset=")
	builder.WriteString(_m.InputDataset)
	builder.WriteString(", ")
	builder.WriteString("input_schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputSchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("params_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParamsJSON))
	builder.WriteString(", ")
	builder.WriteString("data_from=")
	builder.WriteString(_m.DataFrom)
	builder.WriteString(", ")
	builder.WriteString("data_to=")
	builder.WriteString(_m.DataTo)
	builder.WriteString(", ")
	builder.WriteString("data_as_of=")
	builder.WriteString(_m.DataAsOf)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("result_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultCount))
	builder.WriteString(", ")
	builder.WriteString("result_hash=")
	builder.WriteString(_m.ResultHash)
	builder.WriteString(", ")
	builder.WriteString("result_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("summary_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.SummaryJSON))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// ScreenRuns is a parsable slice of ScreenRun.
type ScreenRuns []*ScreenRun
