// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
	"github.com/ev3rlit/mwosa/storage/ent/screenrunitem"
)

// ScreenRunItemDelete is the builder for deleting a ScreenRunItem entity.
type ScreenRunItemDelete struct {
	config
	hooks    []Hook
	mutation *ScreenRunItemMutation
}

// Where appends a list predicates to the ScreenRunItemDelete builder.
func (_d *ScreenRunItemDelete) Where(ps ...predicate.ScreenRunItem) *ScreenRunItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ScreenRunItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScreenRunItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ScreenRunItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(screenrunitem.Table, sqlgraph.NewFieldSpec(screenrunitem.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ScreenRunItemDeleteOne is the builder for deleting a single ScreenRunItem entity.
type ScreenRunItemDeleteOne struct {
	_d *ScreenRunItemDelete
}

// Where appends a list predicates to the ScreenRunItemDelete builder.
func (_d *ScreenRunItemDeleteOne) Where(ps ...predicate.ScreenRunItem) *ScreenRunItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ScreenRunItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{screenrunitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScreenRunItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
