// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
	"github.com/ev3rlit/mwosa/storage/ent/screenrun"
)

// ScreenRunUpdate is the builder for updating ScreenRun entities.
type ScreenRunUpdate struct {
	config
	hooks    []Hook
	mutation *ScreenRunMutation
}

// Where appends a list predicates to the ScreenRunUpdate builder.
func (_u *ScreenRunUpdate) Where(ps ...predicate.ScreenRun) *ScreenRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *ScreenRunUpdate) SetAlias(v string) *ScreenRunUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableAlias(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *ScreenRunUpdate) ClearAlias() *ScreenRunUpdate {
	_u.mutation.ClearAlias()
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *ScreenRunUpdate) SetStrategyID(v string) *ScreenRunUpdate {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableStrategyID(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (_u *ScreenRunUpdate) SetStrategyVersionID(v string) *ScreenRunUpdate {
	_u.mutation.SetStrategyVersionID(v)
	return _u
}

// SetNillableStrategyVersionID sets the "strategy_version_id" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableStrategyVersionID(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetStrategyVersionID(*v)
	}
	return _u
}

// SetQueryHash sets the "query_hash" field.
func (_u *ScreenRunUpdate) SetQueryHash(v string) *ScreenRunUpdate {
	_u.mutation.SetQueryHash(v)
	return _u
}

// SetNillableQueryHash sets the "query_hash" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableQueryHash(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetQueryHash(*v)
	}
	return _u
}

// SetInputDataset sets the "input_dataset" field.
func (_u *ScreenRunUpdate) SetInputDataset(v string) *ScreenRunUpdate {
	_u.mutation.SetInputDataset(v)
	return _u
}

// SetNillableInputDataset sets the "input_dataset" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableInputDataset(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetInputDataset(*v)
	}
	return _u
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (_u *ScreenRunUpdate) SetInputSchemaVersion(v int) *ScreenRunUpdate {
	_u.mutation.ResetInputSchemaVersion()
	_u.mutation.SetInputSchemaVersion(v)
	return _u
}

// SetNillableInputSchemaVersion sets the "input_schema_version" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableInputSchemaVersion(v *int) *ScreenRunUpdate {
	if v != nil {
		_u.SetInputSchemaVersion(*v)
	}
	return _u
}

// AddInputSchemaVersion adds value to the "input_schema_version" field.
func (_u *ScreenRunUpdate) AddInputSchemaVersion(v int) *ScreenRunUpdate {
	_u.mutation.AddInputSchemaVersion(v)
	return _u
}

// SetParamsJSON sets the "params_json" field.
func (_u *ScreenRunUpdate) SetParamsJSON(v []byte) *ScreenRunUpdate {
	_u.mutation.SetParamsJSON(v)
	return _u
}

// ClearParamsJSON clears the value of the "params_json" field.
func (_u *ScreenRunUpdate) ClearParamsJSON() *ScreenRunUpdate {
	_u.mutation.ClearParamsJSON()
	return _u
}

// SetDataFrom sets the "data_from" field.
func (_u *ScreenRunUpdate) SetDataFrom(v string) *ScreenRunUpdate {
	_u.mutation.SetDataFrom(v)
	return _u
}

// SetNillableDataFrom sets the "data_from" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableDataFrom(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetDataFrom(*v)
	}
	return _u
}

// SetDataTo sets the "data_to" field.
func (_u *ScreenRunUpdate) SetDataTo(v string) *ScreenRunUpdate {
	_u.mutation.SetDataTo(v)
	return _u
}

// SetNillableDataTo sets the "data_to" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableDataTo(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetDataTo(*v)
	}
	return _u
}

// SetDataAsOf sets the "data_as_of" field.
func (_u *ScreenRunUpdate) SetDataAsOf(v string) *ScreenRunUpdate {
	_u.mutation.SetDataAsOf(v)
	return _u
}

// SetNillableDataAsOf sets the "data_as_of" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableDataAsOf(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetDataAsOf(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ScreenRunUpdate) SetFinishedAt(v time.Time) *ScreenRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableFinishedAt(v *time.Time) *ScreenRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ScreenRunUpdate) ClearFinishedAt() *ScreenRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScreenRunUpdate) SetStatus(v string) *ScreenRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableStatus(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultCount sets the "result_count" field.
func (_u *ScreenRunUpdate) SetResultCount(v int) *ScreenRunUpdate {
	_u.mutation.ResetResultCount()
	_u.mutation.SetResultCount(v)
	return _u
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableResultCount(v *int) *ScreenRunUpdate {
	if v != nil {
		_u.SetResultCount(*v)
	}
	return _u
}

// AddResultCount adds value to the "result_count" field.
func (_u *ScreenRunUpdate) AddResultCount(v int) *ScreenRunUpdate {
	_u.mutation.AddResultCount(v)
	return _u
}

// SetResultHash sets the "result_hash" field.
func (_u *ScreenRunUpdate) SetResultHash(v string) *ScreenRunUpdate {
	_u.mutation.SetResultHash(v)
	return _u
}

// SetNillableResultHash sets the "result_hash" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableResultHash(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetResultHash(*v)
	}
	return _u
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (_u *ScreenRunUpdate) SetResultSizeBytes(v int64) *ScreenRunUpdate {
	_u.mutation.ResetResultSizeBytes()
	_u.mutation.SetResultSizeBytes(v)
	return _u
}

// SetNillableResultSizeBytes sets the "result_size_bytes" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableResultSizeBytes(v *int64) *ScreenRunUpdate {
	if v != nil {
		_u.SetResultSizeBytes(*v)
	}
	return _u
}

// AddResultSizeBytes adds value to the "result_size_bytes" field.
func (_u *ScreenRunUpdate) AddResultSizeBytes(v int64) *ScreenRunUpdate {
	_u.mutation.AddResultSizeBytes(v)
	return _u
}

// SetSummaryJSON sets the "summary_json" field.
func (_u *ScreenRunUpdate) SetSummaryJSON(v []byte) *ScreenRunUpdate {
	_u.mutation.SetSummaryJSON(v)
	return _u
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (_u *ScreenRunUpdate) ClearSummaryJSON() *ScreenRunUpdate {
	_u.mutation.ClearSummaryJSON()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScreenRunUpdate) SetErrorMessage(v string) *ScreenRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScreenRunUpdate) SetNillableErrorMessage(v *string) *ScreenRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// Mutation returns the ScreenRunMutation object of the builder.
func (_u *ScreenRunUpdate) Mutation() *ScreenRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScreenRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScreenRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScreenRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScreenRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScreenRunUpdate) check() error {
	if v, ok := _u.mutation.StrategyID(); ok {
		if err := screenrun.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyVersionID(); ok {
		if err := screenrun.StrategyVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_version_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QueryHash(); ok {
		if err := screenrun.QueryHashValidator(v); err != nil {
			return &ValidationError{Name: "query_hash", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.query_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputDataset(); ok {
		if err := screenrun.InputDatasetValidator(v); err != nil {
			return &ValidationError{Name: "input_dataset", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_dataset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputSchemaVersion(); ok {
		if err := screenrun.InputSchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "input_schema_version", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_schema_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := screenrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultCount(); ok {
		if err := screenrun.ResultCountValidator(v); err != nil {
			return &ValidationError{Name: "result_count", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultSizeBytes(); ok {
		if err := screenrun.ResultSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "result_size_bytes", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *ScreenRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(screenrun.Table, screenrun.Columns, sqlgraph.NewFieldSpec(screenrun.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(screenrun.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(screenrun.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(screenrun.FieldStrategyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StrategyVersionID(); ok {
		_spec.SetField(screenrun.FieldStrategyVersionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueryHash(); ok {
		_spec.SetField(screenrun.FieldQueryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputDataset(); ok {
		_spec.SetField(screenrun.FieldInputDataset, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputSchemaVersion(); ok {
		_spec.SetField(screenrun.FieldInputSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputSchemaVersion(); ok {
		_spec.AddField(screenrun.FieldInputSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParamsJSON(); ok {
		_spec.SetField(screenrun.FieldParamsJSON, field.TypeBytes, value)
	}
	if _u.mutation.ParamsJSONCleared() {
		_spec.ClearField(screenrun.FieldParamsJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.DataFrom(); ok {
		_spec.SetField(screenrun.FieldDataFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataTo(); ok {
		_spec.SetField(screenrun.FieldDataTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataAsOf(); ok {
		_spec.SetField(screenrun.FieldDataAsOf, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(screenrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(screenrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(screenrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultCount(); ok {
		_spec.SetField(screenrun.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultCount(); ok {
		_spec.AddField(screenrun.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResultHash(); ok {
		_spec.SetField(screenrun.FieldResultHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultSizeBytes(); ok {
		_spec.SetField(screenrun.FieldResultSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResultSizeBytes(); ok {
		_spec.AddField(screenrun.FieldResultSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SummaryJSON(); ok {
		_spec.SetField(screenrun.FieldSummaryJSON, field.TypeBytes, value)
	}
	if _u.mutation.SummaryJSONCleared() {
		_spec.ClearField(screenrun.FieldSummaryJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(screenrun.FieldErrorMessage, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{screenrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScreenRunUpdateOne is the builder for updating a single ScreenRun entity.
type ScreenRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScreenRunMutation
}

// SetAlias sets the "alias" field.
func (_u *ScreenRunUpdateOne) SetAlias(v string) *ScreenRunUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableAlias(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *ScreenRunUpdateOne) ClearAlias() *ScreenRunUpdateOne {
	_u.mutation.ClearAlias()
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *ScreenRunUpdateOne) SetStrategyID(v string) *ScreenRunUpdateOne {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableStrategyID(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// SetStrategyVersionID sets the "strategy_version_id" field.
func (_u *ScreenRunUpdateOne) SetStrategyVersionID(v string) *ScreenRunUpdateOne {
	_u.mutation.SetStrategyVersionID(v)
	return _u
}

// SetNillableStrategyVersionID sets the "strategy_version_id" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableStrategyVersionID(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetStrategyVersionID(*v)
	}
	return _u
}

// SetQueryHash sets the "query_hash" field.
func (_u *ScreenRunUpdateOne) SetQueryHash(v string) *ScreenRunUpdateOne {
	_u.mutation.SetQueryHash(v)
	return _u
}

// SetNillableQueryHash sets the "query_hash" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableQueryHash(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetQueryHash(*v)
	}
	return _u
}

// SetInputDataset sets the "input_dataset" field.
func (_u *ScreenRunUpdateOne) SetInputDataset(v string) *ScreenRunUpdateOne {
	_u.mutation.SetInputDataset(v)
	return _u
}

// SetNillableInputDataset sets the "input_dataset" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableInputDataset(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetInputDataset(*v)
	}
	return _u
}

// SetInputSchemaVersion sets the "input_schema_version" field.
func (_u *ScreenRunUpdateOne) SetInputSchemaVersion(v int) *ScreenRunUpdateOne {
	_u.mutation.ResetInputSchemaVersion()
	_u.mutation.SetInputSchemaVersion(v)
	return _u
}

// SetNillableInputSchemaVersion sets the "input_schema_version" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableInputSchemaVersion(v *int) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetInputSchemaVersion(*v)
	}
	return _u
}

// AddInputSchemaVersion adds value to the "input_schema_version" field.
func (_u *ScreenRunUpdateOne) AddInputSchemaVersion(v int) *ScreenRunUpdateOne {
	_u.mutation.AddInputSchemaVersion(v)
	return _u
}

// SetParamsJSON sets the "params_json" field.
func (_u *ScreenRunUpdateOne) SetParamsJSON(v []byte) *ScreenRunUpdateOne {
	_u.mutation.SetParamsJSON(v)
	return _u
}

// ClearParamsJSON clears the value of the "params_json" field.
func (_u *ScreenRunUpdateOne) ClearParamsJSON() *ScreenRunUpdateOne {
	_u.mutation.ClearParamsJSON()
	return _u
}

// SetDataFrom sets the "data_from" field.
func (_u *ScreenRunUpdateOne) SetDataFrom(v string) *ScreenRunUpdateOne {
	_u.mutation.SetDataFrom(v)
	return _u
}

// SetNillableDataFrom sets the "data_from" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableDataFrom(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetDataFrom(*v)
	}
	return _u
}

// SetDataTo sets the "data_to" field.
func (_u *ScreenRunUpdateOne) SetDataTo(v string) *ScreenRunUpdateOne {
	_u.mutation.SetDataTo(v)
	return _u
}

// SetNillableDataTo sets the "data_to" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableDataTo(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetDataTo(*v)
	}
	return _u
}

// SetDataAsOf sets the "data_as_of" field.
func (_u *ScreenRunUpdateOne) SetDataAsOf(v string) *ScreenRunUpdateOne {
	_u.mutation.SetDataAsOf(v)
	return _u
}

// SetNillableDataAsOf sets the "data_as_of" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableDataAsOf(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetDataAsOf(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *ScreenRunUpdateOne) SetFinishedAt(v time.Time) *ScreenRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableFinishedAt(v *time.Time) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *ScreenRunUpdateOne) ClearFinishedAt() *ScreenRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScreenRunUpdateOne) SetStatus(v string) *ScreenRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableStatus(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultCount sets the "result_count" field.
func (_u *ScreenRunUpdateOne) SetResultCount(v int) *ScreenRunUpdateOne {
	_u.mutation.ResetResultCount()
	_u.mutation.SetResultCount(v)
	return _u
}

// SetNillableResultCount sets the "result_count" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableResultCount(v *int) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetResultCount(*v)
	}
	return _u
}

// AddResultCount adds value to the "result_count" field.
func (_u *ScreenRunUpdateOne) AddResultCount(v int) *ScreenRunUpdateOne {
	_u.mutation.AddResultCount(v)
	return _u
}

// SetResultHash sets the "result_hash" field.
func (_u *ScreenRunUpdateOne) SetResultHash(v string) *ScreenRunUpdateOne {
	_u.mutation.SetResultHash(v)
	return _u
}

// SetNillableResultHash sets the "result_hash" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableResultHash(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetResultHash(*v)
	}
	return _u
}

// SetResultSizeBytes sets the "result_size_bytes" field.
func (_u *ScreenRunUpdateOne) SetResultSizeBytes(v int64) *ScreenRunUpdateOne {
	_u.mutation.ResetResultSizeBytes()
	_u.mutation.SetResultSizeBytes(v)
	return _u
}

// SetNillableResultSizeBytes sets the "result_size_bytes" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableResultSizeBytes(v *int64) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetResultSizeBytes(*v)
	}
	return _u
}

// AddResultSizeBytes adds value to the "result_size_bytes" field.
func (_u *ScreenRunUpdateOne) AddResultSizeBytes(v int64) *ScreenRunUpdateOne {
	_u.mutation.AddResultSizeBytes(v)
	return _u
}

// SetSummaryJSON sets the "summary_json" field.
func (_u *ScreenRunUpdateOne) SetSummaryJSON(v []byte) *ScreenRunUpdateOne {
	_u.mutation.SetSummaryJSON(v)
	return _u
}

// ClearSummaryJSON clears the value of the "summary_json" field.
func (_u *ScreenRunUpdateOne) ClearSummaryJSON() *ScreenRunUpdateOne {
	_u.mutation.ClearSummaryJSON()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScreenRunUpdateOne) SetErrorMessage(v string) *ScreenRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScreenRunUpdateOne) SetNillableErrorMessage(v *string) *ScreenRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// Mutation returns the ScreenRunMutation object of the builder.
func (_u *ScreenRunUpdateOne) Mutation() *ScreenRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScreenRunUpdate builder.
func (_u *ScreenRunUpdateOne) Where(ps ...predicate.ScreenRun) *ScreenRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScreenRunUpdateOne) Select(field string, fields ...string) *ScreenRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScreenRun entity.
func (_u *ScreenRunUpdateOne) Save(ctx context.Context) (*ScreenRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScreenRunUpdateOne) SaveX(ctx context.Context) *ScreenRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScreenRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScreenRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScreenRunUpdateOne) check() error {
	if v, ok := _u.mutation.StrategyID(); ok {
		if err := screenrun.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyVersionID(); ok {
		if err := screenrun.StrategyVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version_id", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.strategy_version_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QueryHash(); ok {
		if err := screenrun.QueryHashValidator(v); err != nil {
			return &ValidationError{Name: "query_hash", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.query_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputDataset(); ok {
		if err := screenrun.InputDatasetValidator(v); err != nil {
			return &ValidationError{Name: "input_dataset", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_dataset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputSchemaVersion(); ok {
		if err := screenrun.InputSchemaVersionValidator(v); err != nil {
			return &ValidationError{Name: "input_schema_version", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.input_schema_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := screenrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultCount(); ok {
		if err := screenrun.ResultCountValidator(v); err != nil {
			return &ValidationError{Name: "result_count", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultSizeBytes(); ok {
		if err := screenrun.ResultSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "result_size_bytes", err: fmt.Errorf(`ent: validator failed for field "ScreenRun.result_size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *ScreenRunUpdateOne) sqlSave(ctx context.Context) (_node *ScreenRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(screenrun.Table, screenrun.Columns, sqlgraph.NewFieldSpec(screenrun.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScreenRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, screenrun.FieldID)
		for _, f := range fields {
			if !screenrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != screenrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(screenrun.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(screenrun.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(screenrun.FieldStrategyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StrategyVersionID(); ok {
		_spec.SetField(screenrun.FieldStrategyVersionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueryHash(); ok {
		_spec.SetField(screenrun.FieldQueryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputDataset(); ok {
		_spec.SetField(screenrun.FieldInputDataset, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputSchemaVersion(); ok {
		_spec.SetField(screenrun.FieldInputSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputSchemaVersion(); ok {
		_spec.AddField(screenrun.FieldInputSchemaVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParamsJSON(); ok {
		_spec.SetField(screenrun.FieldParamsJSON, field.TypeBytes, value)
	}
	if _u.mutation.ParamsJSONCleared() {
		_spec.ClearField(screenrun.FieldParamsJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.DataFrom(); ok {
		_spec.SetField(screenrun.FieldDataFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataTo(); ok {
		_spec.SetField(screenrun.FieldDataTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataAsOf(); ok {
		_spec.SetField(screenrun.FieldDataAsOf, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(screenrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(screenrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(screenrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultCount(); ok {
		_spec.SetField(screenrun.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResultCount(); ok {
		_spec.AddField(screenrun.FieldResultCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResultHash(); ok {
		_spec.SetField(screenrun.FieldResultHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultSizeBytes(); ok {
		_spec.SetField(screenrun.FieldResultSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResultSizeBytes(); ok {
		_spec.AddField(screenrun.FieldResultSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SummaryJSON(); ok {
		_spec.SetField(screenrun.FieldSummaryJSON, field.TypeBytes, value)
	}
	if _u.mutation.SummaryJSONCleared() {
		_spec.ClearField(screenrun.FieldSummaryJSON, field.TypeBytes)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(screenrun.FieldErrorMessage, field.TypeString, value)
	}
	_node = &ScreenRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{screenrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
