// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
	"github.com/ev3rlit/mwosa/storage/ent/strategy"
)

// StrategyUpdate is the builder for updating Strategy entities.
type StrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyMutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdate) Where(ps ...predicate.Strategy) *StrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StrategyUpdate) SetName(v string) *StrategyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableName(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEngine sets the "engine" field.
func (_u *StrategyUpdate) SetEngine(v string) *StrategyUpdate {
	_u.mutation.SetEngine(v)
	return _u
}

// SetNillableEngine sets the "engine" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEngine(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetEngine(*v)
	}
	return _u
}

// SetActiveVersionID sets the "active_version_id" field.
func (_u *StrategyUpdate) SetActiveVersionID(v string) *StrategyUpdate {
	_u.mutation.SetActiveVersionID(v)
	return _u
}

// SetNillableActiveVersionID sets the "active_version_id" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableActiveVersionID(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetActiveVersionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StrategyUpdate) SetUpdatedAt(v time.Time) *StrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *StrategyUpdate) SetArchivedAt(v time.Time) *StrategyUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableArchivedAt(v *time.Time) *StrategyUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *StrategyUpdate) ClearArchivedAt() *StrategyUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdate) Mutation() *StrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StrategyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := strategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := strategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Strategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Engine(); ok {
		if err := strategy.EngineValidator(v); err != nil {
			return &ValidationError{Name: "engine", err: fmt.Errorf(`ent: validator failed for field "Strategy.engine": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveVersionID(); ok {
		if err := strategy.ActiveVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "active_version_id", err: fmt.Errorf(`ent: validator failed for field "Strategy.active_version_id": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Engine(); ok {
		_spec.SetField(strategy.FieldEngine, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveVersionID(); ok {
		_spec.SetField(strategy.FieldActiveVersionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(strategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(strategy.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(strategy.FieldArchivedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StrategyUpdateOne is the builder for updating a single Strategy entity.
type StrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyMutation
}

// SetName sets the "name" field.
func (_u *StrategyUpdateOne) SetName(v string) *StrategyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableName(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEngine sets the "engine" field.
func (_u *StrategyUpdateOne) SetEngine(v string) *StrategyUpdateOne {
	_u.mutation.SetEngine(v)
	return _u
}

// SetNillableEngine sets the "engine" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEngine(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetEngine(*v)
	}
	return _u
}

// SetActiveVersionID sets the "active_version_id" field.
func (_u *StrategyUpdateOne) SetActiveVersionID(v string) *StrategyUpdateOne {
	_u.mutation.SetActiveVersionID(v)
	return _u
}

// SetNillableActiveVersionID sets the "active_version_id" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableActiveVersionID(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetActiveVersionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StrategyUpdateOne) SetUpdatedAt(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *StrategyUpdateOne) SetArchivedAt(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableArchivedAt(v *time.Time) *StrategyUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *StrategyUpdateOne) ClearArchivedAt() *StrategyUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdateOne) Mutation() *StrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdateOne) Where(ps ...predicate.Strategy) *StrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StrategyUpdateOne) Select(field string, fields ...string) *StrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Strategy entity.
func (_u *StrategyUpdateOne) Save(ctx context.Context) (*Strategy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdateOne) SaveX(ctx context.Context) *Strategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := strategy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := strategy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Strategy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Engine(); ok {
		if err := strategy.EngineValidator(v); err != nil {
			return &ValidationError{Name: "engine", err: fmt.Errorf(`ent: validator failed for field "Strategy.engine": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveVersionID(); ok {
		if err := strategy.ActiveVersionIDValidator(v); err != nil {
			return &ValidationError{Name: "active_version_id", err: fmt.Errorf(`ent: validator failed for field "Strategy.active_version_id": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyUpdateOne) sqlSave(ctx context.Context) (_node *Strategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Strategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategy.FieldID)
		for _, f := range fields {
			if !strategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(strategy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Engine(); ok {
		_spec.SetField(strategy.FieldEngine, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActiveVersionID(); ok {
		_spec.SetField(strategy.FieldActiveVersionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(strategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(strategy.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(strategy.FieldArchivedAt, field.TypeTime)
	}
	_node = &Strategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
