// Code generated by ent, DO NOT EDIT.

package screenrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ev3rlit/mwosa/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldID, id))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldAlias, v))
}

// StrategyID applies equality check predicate on the "strategy_id" field. It's identical to StrategyIDEQ.
func StrategyID(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyVersionID applies equality check predicate on the "strategy_version_id" field. It's identical to StrategyVersionIDEQ.
func StrategyVersionID(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStrategyVersionID, v))
}

// QueryHash applies equality check predicate on the "query_hash" field. It's identical to QueryHashEQ.
func QueryHash(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldQueryHash, v))
}

// InputDataset applies equality check predicate on the "input_dataset" field. It's identical to InputDatasetEQ.
func InputDataset(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldInputDataset, v))
}

// InputSchemaVersion applies equality check predicate on the "input_schema_version" field. It's identical to InputSchemaVersionEQ.
func InputSchemaVersion(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldInputSchemaVersion, v))
}

// ParamsJSON applies equality check predicate on the "params_json" field. It's identical to ParamsJSONEQ.
func ParamsJSON(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldParamsJSON, v))
}

// DataFrom applies equality check predicate on the "data_from" field. It's identical to DataFromEQ.
func DataFrom(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataFrom, v))
}

// DataTo applies equality check predicate on the "data_to" field. It's identical to DataToEQ.
func DataTo(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataTo, v))
}

// DataAsOf applies equality check predicate on the "data_as_of" field. It's identical to DataAsOfEQ.
func DataAsOf(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataAsOf, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldFinishedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStatus, v))
}

// ResultCount applies equality check predicate on the "result_count" field. It's identical to ResultCountEQ.
func ResultCount(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultCount, v))
}

// ResultHash applies equality check predicate on the "result_hash" field. It's identical to ResultHashEQ.
func ResultHash(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultHash, v))
}

// ResultSizeBytes applies equality check predicate on the "result_size_bytes" field. It's identical to ResultSizeBytesEQ.
func ResultSizeBytes(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultSizeBytes, v))
}

// SummaryJSON applies equality check predicate on the "summary_json" field. It's identical to SummaryJSONEQ.
func SummaryJSON(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldSummaryJSON, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldErrorMessage, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasIsNil applies the IsNil predicate on the "alias" field.
func AliasIsNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIsNull(FieldAlias))
}

// AliasNotNil applies the NotNil predicate on the "alias" field.
func AliasNotNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotNull(FieldAlias))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldAlias, v))
}

// StrategyIDEQ applies the EQ predicate on the "strategy_id" field.
func StrategyIDEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyIDNEQ applies the NEQ predicate on the "strategy_id" field.
func StrategyIDNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldStrategyID, v))
}

// StrategyIDIn applies the In predicate on the "strategy_id" field.
func StrategyIDIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldStrategyID, vs...))
}

// StrategyIDNotIn applies the NotIn predicate on the "strategy_id" field.
func StrategyIDNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldStrategyID, vs...))
}

// StrategyIDGT applies the GT predicate on the "strategy_id" field.
func StrategyIDGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldStrategyID, v))
}

// StrategyIDGTE applies the GTE predicate on the "strategy_id" field.
func StrategyIDGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldStrategyID, v))
}

// StrategyIDLT applies the LT predicate on the "strategy_id" field.
func StrategyIDLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldStrategyID, v))
}

// StrategyIDLTE applies the LTE predicate on the "strategy_id" field.
func StrategyIDLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldStrategyID, v))
}

// StrategyIDContains applies the Contains predicate on the "strategy_id" field.
func StrategyIDContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldStrategyID, v))
}

// StrategyIDHasPrefix applies the HasPrefix predicate on the "strategy_id" field.
func StrategyIDHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldStrategyID, v))
}

// StrategyIDHasSuffix applies the HasSuffix predicate on the "strategy_id" field.
func StrategyIDHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldStrategyID, v))
}

// StrategyIDEqualFold applies the EqualFold predicate on the "strategy_id" field.
func StrategyIDEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldStrategyID, v))
}

// StrategyIDContainsFold applies the ContainsFold predicate on the "strategy_id" field.
func StrategyIDContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldStrategyID, v))
}

// StrategyVersionIDEQ applies the EQ predicate on the "strategy_version_id" field.
func StrategyVersionIDEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStrategyVersionID, v))
}

// StrategyVersionIDNEQ applies the NEQ predicate on the "strategy_version_id" field.
func StrategyVersionIDNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldStrategyVersionID, v))
}

// StrategyVersionIDIn applies the In predicate on the "strategy_version_id" field.
func StrategyVersionIDIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldStrategyVersionID, vs...))
}

// StrategyVersionIDNotIn applies the NotIn predicate on the "strategy_version_id" field.
func StrategyVersionIDNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldStrategyVersionID, vs...))
}

// StrategyVersionIDGT applies the GT predicate on the "strategy_version_id" field.
func StrategyVersionIDGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldStrategyVersionID, v))
}

// StrategyVersionIDGTE applies the GTE predicate on the "strategy_version_id" field.
func StrategyVersionIDGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldStrategyVersionID, v))
}

// StrategyVersionIDLT applies the LT predicate on the "strategy_version_id" field.
func StrategyVersionIDLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldStrategyVersionID, v))
}

// StrategyVersionIDLTE applies the LTE predicate on the "strategy_version_id" field.
func StrategyVersionIDLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldStrategyVersionID, v))
}

// StrategyVersionIDContains applies the Contains predicate on the "strategy_version_id" field.
func StrategyVersionIDContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldStrategyVersionID, v))
}

// StrategyVersionIDHasPrefix applies the HasPrefix predicate on the "strategy_version_id" field.
func StrategyVersionIDHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldStrategyVersionID, v))
}

// StrategyVersionIDHasSuffix applies the HasSuffix predicate on the "strategy_version_id" field.
func StrategyVersionIDHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldStrategyVersionID, v))
}

// StrategyVersionIDEqualFold applies the EqualFold predicate on the "strategy_version_id" field.
func StrategyVersionIDEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldStrategyVersionID, v))
}

// StrategyVersionIDContainsFold applies the ContainsFold predicate on the "strategy_version_id" field.
func StrategyVersionIDContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldStrategyVersionID, v))
}

// QueryHashEQ applies the EQ predicate on the "query_hash" field.
func QueryHashEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldQueryHash, v))
}

// QueryHashNEQ applies the NEQ predicate on the "query_hash" field.
func QueryHashNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldQueryHash, v))
}

// QueryHashIn applies the In predicate on the "query_hash" field.
func QueryHashIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldQueryHash, vs...))
}

// QueryHashNotIn applies the NotIn predicate on the "query_hash" field.
func QueryHashNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldQueryHash, vs...))
}

// QueryHashGT applies the GT predicate on the "query_hash" field.
func QueryHashGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldQueryHash, v))
}

// QueryHashGTE applies the GTE predicate on the "query_hash" field.
func QueryHashGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldQueryHash, v))
}

// QueryHashLT applies the LT predicate on the "query_hash" field.
func QueryHashLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldQueryHash, v))
}

// QueryHashLTE applies the LTE predicate on the "query_hash" field.
func QueryHashLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldQueryHash, v))
}

// QueryHashContains applies the Contains predicate on the "query_hash" field.
func QueryHashContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldQueryHash, v))
}

// QueryHashHasPrefix applies the HasPrefix predicate on the "query_hash" field.
func QueryHashHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldQueryHash, v))
}

// QueryHashHasSuffix applies the HasSuffix predicate on the "query_hash" field.
func QueryHashHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldQueryHash, v))
}

// QueryHashEqualFold applies the EqualFold predicate on the "query_hash" field.
func QueryHashEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldQueryHash, v))
}

// QueryHashContainsFold applies the ContainsFold predicate on the "query_hash" field.
func QueryHashContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldQueryHash, v))
}

// InputDatasetEQ applies the EQ predicate on the "input_dataset" field.
func InputDatasetEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldInputDataset, v))
}

// InputDatasetNEQ applies the NEQ predicate on the "input_dataset" field.
func InputDatasetNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldInputDataset, v))
}

// InputDatasetIn applies the In predicate on the "input_dataset" field.
func InputDatasetIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldInputDataset, vs...))
}

// InputDatasetNotIn applies the NotIn predicate on the "input_dataset" field.
func InputDatasetNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldInputDataset, vs...))
}

// InputDatasetGT applies the GT predicate on the "input_dataset" field.
func InputDatasetGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldInputDataset, v))
}

// InputDatasetGTE applies the GTE predicate on the "input_dataset" field.
func InputDatasetGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldInputDataset, v))
}

// InputDatasetLT applies the LT predicate on the "input_dataset" field.
func InputDatasetLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldInputDataset, v))
}

// InputDatasetLTE applies the LTE predicate on the "input_dataset" field.
func InputDatasetLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldInputDataset, v))
}

// InputDatasetContains applies the Contains predicate on the "input_dataset" field.
func InputDatasetContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldInputDataset, v))
}

// InputDatasetHasPrefix applies the HasPrefix predicate on the "input_dataset" field.
func InputDatasetHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldInputDataset, v))
}

// InputDatasetHasSuffix applies the HasSuffix predicate on the "input_dataset" field.
func InputDatasetHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldInputDataset, v))
}

// InputDatasetEqualFold applies the EqualFold predicate on the "input_dataset" field.
func InputDatasetEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldInputDataset, v))
}

// InputDatasetContainsFold applies the ContainsFold predicate on the "input_dataset" field.
func InputDatasetContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldInputDataset, v))
}

// InputSchemaVersionEQ applies the EQ predicate on the "input_schema_version" field.
func InputSchemaVersionEQ(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldInputSchemaVersion, v))
}

// InputSchemaVersionNEQ applies the NEQ predicate on the "input_schema_version" field.
func InputSchemaVersionNEQ(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldInputSchemaVersion, v))
}

// InputSchemaVersionIn applies the In predicate on the "input_schema_version" field.
func InputSchemaVersionIn(vs ...int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldInputSchemaVersion, vs...))
}

// InputSchemaVersionNotIn applies the NotIn predicate on the "input_schema_version" field.
func InputSchemaVersionNotIn(vs ...int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldInputSchemaVersion, vs...))
}

// InputSchemaVersionGT applies the GT predicate on the "input_schema_version" field.
func InputSchemaVersionGT(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldInputSchemaVersion, v))
}

// InputSchemaVersionGTE applies the GTE predicate on the "input_schema_version" field.
func InputSchemaVersionGTE(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldInputSchemaVersion, v))
}

// InputSchemaVersionLT applies the LT predicate on the "input_schema_version" field.
func InputSchemaVersionLT(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldInputSchemaVersion, v))
}

// InputSchemaVersionLTE applies the LTE predicate on the "input_schema_version" field.
func InputSchemaVersionLTE(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldInputSchemaVersion, v))
}

// ParamsJSONEQ applies the EQ predicate on the "params_json" field.
func ParamsJSONEQ(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldParamsJSON, v))
}

// ParamsJSONNEQ applies the NEQ predicate on the "params_json" field.
func ParamsJSONNEQ(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldParamsJSON, v))
}

// ParamsJSONIn applies the In predicate on the "params_json" field.
func ParamsJSONIn(vs ...[]byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldParamsJSON, vs...))
}

// ParamsJSONNotIn applies the NotIn predicate on the "params_json" field.
func ParamsJSONNotIn(vs ...[]byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldParamsJSON, vs...))
}

// ParamsJSONGT applies the GT predicate on the "params_json" field.
func ParamsJSONGT(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldParamsJSON, v))
}

// ParamsJSONGTE applies the GTE predicate on the "params_json" field.
func ParamsJSONGTE(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldParamsJSON, v))
}

// ParamsJSONLT applies the LT predicate on the "params_json" field.
func ParamsJSONLT(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldParamsJSON, v))
}

// ParamsJSONLTE applies the LTE predicate on the "params_json" field.
func ParamsJSONLTE(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldParamsJSON, v))
}

// ParamsJSONIsNil applies the IsNil predicate on the "params_json" field.
func ParamsJSONIsNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIsNull(FieldParamsJSON))
}

// ParamsJSONNotNil applies the NotNil predicate on the "params_json" field.
func ParamsJSONNotNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotNull(FieldParamsJSON))
}

// DataFromEQ applies the EQ predicate on the "data_from" field.
func DataFromEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataFrom, v))
}

// DataFromNEQ applies the NEQ predicate on the "data_from" field.
func DataFromNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldDataFrom, v))
}

// DataFromIn applies the In predicate on the "data_from" field.
func DataFromIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldDataFrom, vs...))
}

// DataFromNotIn applies the NotIn predicate on the "data_from" field.
func DataFromNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldDataFrom, vs...))
}

// DataFromGT applies the GT predicate on the "data_from" field.
func DataFromGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldDataFrom, v))
}

// DataFromGTE applies the GTE predicate on the "data_from" field.
func DataFromGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldDataFrom, v))
}

// DataFromLT applies the LT predicate on the "data_from" field.
func DataFromLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldDataFrom, v))
}

// DataFromLTE applies the LTE predicate on the "data_from" field.
func DataFromLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldDataFrom, v))
}

// DataFromContains applies the Contains predicate on the "data_from" field.
func DataFromContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldDataFrom, v))
}

// DataFromHasPrefix applies the HasPrefix predicate on the "data_from" field.
func DataFromHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldDataFrom, v))
}

// DataFromHasSuffix applies the HasSuffix predicate on the "data_from" field.
func DataFromHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldDataFrom, v))
}

// DataFromEqualFold applies the EqualFold predicate on the "data_from" field.
func DataFromEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldDataFrom, v))
}

// DataFromContainsFold applies the ContainsFold predicate on the "data_from" field.
func DataFromContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldDataFrom, v))
}

// DataToEQ applies the EQ predicate on the "data_to" field.
func DataToEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataTo, v))
}

// DataToNEQ applies the NEQ predicate on the "data_to" field.
func DataToNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldDataTo, v))
}

// DataToIn applies the In predicate on the "data_to" field.
func DataToIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldDataTo, vs...))
}

// DataToNotIn applies the NotIn predicate on the "data_to" field.
func DataToNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldDataTo, vs...))
}

// DataToGT applies the GT predicate on the "data_to" field.
func DataToGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldDataTo, v))
}

// DataToGTE applies the GTE predicate on the "data_to" field.
func DataToGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldDataTo, v))
}

// DataToLT applies the LT predicate on the "data_to" field.
func DataToLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldDataTo, v))
}

// DataToLTE applies the LTE predicate on the "data_to" field.
func DataToLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldDataTo, v))
}

// DataToContains applies the Contains predicate on the "data_to" field.
func DataToContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldDataTo, v))
}

// DataToHasPrefix applies the HasPrefix predicate on the "data_to" field.
func DataToHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldDataTo, v))
}

// DataToHasSuffix applies the HasSuffix predicate on the "data_to" field.
func DataToHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldDataTo, v))
}

// DataToEqualFold applies the EqualFold predicate on the "data_to" field.
func DataToEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldDataTo, v))
}

// DataToContainsFold applies the ContainsFold predicate on the "data_to" field.
func DataToContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldDataTo, v))
}

// DataAsOfEQ applies the EQ predicate on the "data_as_of" field.
func DataAsOfEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldDataAsOf, v))
}

// DataAsOfNEQ applies the NEQ predicate on the "data_as_of" field.
func DataAsOfNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldDataAsOf, v))
}

// DataAsOfIn applies the In predicate on the "data_as_of" field.
func DataAsOfIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldDataAsOf, vs...))
}

// DataAsOfNotIn applies the NotIn predicate on the "data_as_of" field.
func DataAsOfNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldDataAsOf, vs...))
}

// DataAsOfGT applies the GT predicate on the "data_as_of" field.
func DataAsOfGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldDataAsOf, v))
}

// DataAsOfGTE applies the GTE predicate on the "data_as_of" field.
func DataAsOfGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldDataAsOf, v))
}

// DataAsOfLT applies the LT predicate on the "data_as_of" field.
func DataAsOfLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldDataAsOf, v))
}

// DataAsOfLTE applies the LTE predicate on the "data_as_of" field.
func DataAsOfLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldDataAsOf, v))
}

// DataAsOfContains applies the Contains predicate on the "data_as_of" field.
func DataAsOfContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldDataAsOf, v))
}

// DataAsOfHasPrefix applies the HasPrefix predicate on the "data_as_of" field.
func DataAsOfHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldDataAsOf, v))
}

// DataAsOfHasSuffix applies the HasSuffix predicate on the "data_as_of" field.
func DataAsOfHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldDataAsOf, v))
}

// DataAsOfEqualFold applies the EqualFold predicate on the "data_as_of" field.
func DataAsOfEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldDataAsOf, v))
}

// DataAsOfContainsFold applies the ContainsFold predicate on the "data_as_of" field.
func DataAsOfContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldDataAsOf, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotNull(FieldFinishedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldStatus, v))
}

// ResultCountEQ applies the EQ predicate on the "result_count" field.
func ResultCountEQ(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultCount, v))
}

// ResultCountNEQ applies the NEQ predicate on the "result_count" field.
func ResultCountNEQ(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldResultCount, v))
}

// ResultCountIn applies the In predicate on the "result_count" field.
func ResultCountIn(vs ...int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldResultCount, vs...))
}

// ResultCountNotIn applies the NotIn predicate on the "result_count" field.
func ResultCountNotIn(vs ...int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldResultCount, vs...))
}

// ResultCountGT applies the GT predicate on the "result_count" field.
func ResultCountGT(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldResultCount, v))
}

// ResultCountGTE applies the GTE predicate on the "result_count" field.
func ResultCountGTE(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldResultCount, v))
}

// ResultCountLT applies the LT predicate on the "result_count" field.
func ResultCountLT(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldResultCount, v))
}

// ResultCountLTE applies the LTE predicate on the "result_count" field.
func ResultCountLTE(v int) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldResultCount, v))
}

// ResultHashEQ applies the EQ predicate on the "result_hash" field.
func ResultHashEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultHash, v))
}

// ResultHashNEQ applies the NEQ predicate on the "result_hash" field.
func ResultHashNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldResultHash, v))
}

// ResultHashIn applies the In predicate on the "result_hash" field.
func ResultHashIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldResultHash, vs...))
}

// ResultHashNotIn applies the NotIn predicate on the "result_hash" field.
func ResultHashNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldResultHash, vs...))
}

// ResultHashGT applies the GT predicate on the "result_hash" field.
func ResultHashGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldResultHash, v))
}

// ResultHashGTE applies the GTE predicate on the "result_hash" field.
func ResultHashGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldResultHash, v))
}

// ResultHashLT applies the LT predicate on the "result_hash" field.
func ResultHashLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldResultHash, v))
}

// ResultHashLTE applies the LTE predicate on the "result_hash" field.
func ResultHashLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldResultHash, v))
}

// ResultHashContains applies the Contains predicate on the "result_hash" field.
func ResultHashContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldResultHash, v))
}

// ResultHashHasPrefix applies the HasPrefix predicate on the "result_hash" field.
func ResultHashHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldResultHash, v))
}

// ResultHashHasSuffix applies the HasSuffix predicate on the "result_hash" field.
func ResultHashHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldResultHash, v))
}

// ResultHashEqualFold applies the EqualFold predicate on the "result_hash" field.
func ResultHashEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldResultHash, v))
}

// ResultHashContainsFold applies the ContainsFold predicate on the "result_hash" field.
func ResultHashContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldResultHash, v))
}

// ResultSizeBytesEQ applies the EQ predicate on the "result_size_bytes" field.
func ResultSizeBytesEQ(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldResultSizeBytes, v))
}

// ResultSizeBytesNEQ applies the NEQ predicate on the "result_size_bytes" field.
func ResultSizeBytesNEQ(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldResultSizeBytes, v))
}

// ResultSizeBytesIn applies the In predicate on the "result_size_bytes" field.
func ResultSizeBytesIn(vs ...int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldResultSizeBytes, vs...))
}

// ResultSizeBytesNotIn applies the NotIn predicate on the "result_size_bytes" field.
func ResultSizeBytesNotIn(vs ...int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldResultSizeBytes, vs...))
}

// ResultSizeBytesGT applies the GT predicate on the "result_size_bytes" field.
func ResultSizeBytesGT(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldResultSizeBytes, v))
}

// ResultSizeBytesGTE applies the GTE predicate on the "result_size_bytes" field.
func ResultSizeBytesGTE(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldResultSizeBytes, v))
}

// ResultSizeBytesLT applies the LT predicate on the "result_size_bytes" field.
func ResultSizeBytesLT(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldResultSizeBytes, v))
}

// ResultSizeBytesLTE applies the LTE predicate on the "result_size_bytes" field.
func ResultSizeBytesLTE(v int64) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldResultSizeBytes, v))
}

// SummaryJSONEQ applies the EQ predicate on the "summary_json" field.
func SummaryJSONEQ(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldSummaryJSON, v))
}

// SummaryJSONNEQ applies the NEQ predicate on the "summary_json" field.
func SummaryJSONNEQ(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldSummaryJSON, v))
}

// SummaryJSONIn applies the In predicate on the "summary_json" field.
func SummaryJSONIn(vs ...[]byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldSummaryJSON, vs...))
}

// SummaryJSONNotIn applies the NotIn predicate on the "summary_json" field.
func SummaryJSONNotIn(vs ...[]byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldSummaryJSON, vs...))
}

// SummaryJSONGT applies the GT predicate on the "summary_json" field.
func SummaryJSONGT(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldSummaryJSON, v))
}

// SummaryJSONGTE applies the GTE predicate on the "summary_json" field.
func SummaryJSONGTE(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldSummaryJSON, v))
}

// SummaryJSONLT applies the LT predicate on the "summary_json" field.
func SummaryJSONLT(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldSummaryJSON, v))
}

// SummaryJSONLTE applies the LTE predicate on the "summary_json" field.
func SummaryJSONLTE(v []byte) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldSummaryJSON, v))
}

// SummaryJSONIsNil applies the IsNil predicate on the "summary_json" field.
func SummaryJSONIsNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIsNull(FieldSummaryJSON))
}

// SummaryJSONNotNil applies the NotNil predicate on the "summary_json" field.
func SummaryJSONNotNil() predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotNull(FieldSummaryJSON))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ScreenRun {
	return predicate.ScreenRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScreenRun) predicate.ScreenRun {
	return predicate.ScreenRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScreenRun) predicate.ScreenRun {
	return predicate.ScreenRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScreenRun) predicate.ScreenRun {
	return predicate.ScreenRun(sql.NotPredicates(p))
}
